"""empty message

Revision ID: 06ee9da93d69
Revises: b2c3d4e5f6a7
Create Date: 2026-05-12 08:26:18.521342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06ee9da93d69'
down_revision = 'b2c3d4e5f6a7'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('corpus_custom_dictionary', schema=None) as batch_op:
        batch_op.alter_column('label',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=1024),
               existing_nullable=False)
        batch_op.alter_column('secondary_label',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=1024),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('corpus_custom_dictionary', schema=None) as batch_op:
        batch_op.alter_column('secondary_label',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.alter_column('label',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
