"""Add gloss column to word_token and change_record

Revision ID: 1033432bf435
Revises: c3f233d4768e
Create Date: 2026-04-28 08:44:36.469354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1033432bf435'
down_revision = 'c3f233d4768e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('change_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gloss', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('gloss_new', sa.String(length=512), nullable=True))

    with op.batch_alter_table('word_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gloss', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word_token', schema=None) as batch_op:
        batch_op.drop_column('gloss')

    with op.batch_alter_table('change_record', schema=None) as batch_op:
        batch_op.drop_column('gloss_new')
        batch_op.drop_column('gloss')

    # ### end Alembic commands ###
