"""Initial schema

Revision ID: 5825ee1a86fe
Revises: 
Create Date: 2026-04-27 21:26:22.687055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5825ee1a86fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('control_lists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('public', sa.Enum('public', 'submitted', 'private', name='publicationstatus'), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('bibliography', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['control_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('index', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_default'), ['default'], unique=False)

    op.create_table('allowed_lemma',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('label_uniform', sa.String(length=128), nullable=True),
    sa.Column('control_list', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['control_list'], ['control_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('allowed_lemma', schema=None) as batch_op:
        batch_op.create_index('unique_label_per_control', ['label', 'control_list'], unique=True)

    op.create_table('allowed_morph',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('readable', sa.String(length=256), nullable=True),
    sa.Column('control_list', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['control_list'], ['control_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('allowed_pos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('control_list', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['control_list'], ['control_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corpus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('context_left', sa.SmallInteger(), nullable=True),
    sa.Column('context_right', sa.SmallInteger(), nullable=True),
    sa.Column('control_lists_id', sa.Integer(), nullable=False),
    sa.Column('delimiter_token', sa.String(length=12), nullable=True),
    sa.ForeignKeyConstraint(['control_lists_id'], ['control_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=162), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_last_name'), ['last_name'], unique=False)

    op.create_table('column',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('corpus_id', sa.Integer(), nullable=True),
    sa.Column('heading', sa.String(length=32), nullable=True),
    sa.Column('hidden', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['corpus_id'], ['corpus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('control_lists_user',
    sa.Column('control_lists_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['control_lists_id'], ['control_lists.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('control_lists_id', 'user_id')
    )
    op.create_table('corpus_custom_dictionary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('corpus', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('secondary_label', sa.String(length=128), nullable=True),
    sa.Column('category', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['corpus'], ['corpus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corpus_user',
    sa.Column('corpus_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['corpus_id'], ['corpus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('corpus_id', 'user_id')
    )
    op.create_table('favorite',
    sa.Column('corpus_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['corpus_id'], ['corpus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('corpus_id', 'user_id')
    )
    op.create_table('word_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('corpus', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('form', sa.String(length=128), nullable=True),
    sa.Column('lemma', sa.String(length=128), nullable=True),
    sa.Column('label_uniform', sa.String(length=128), nullable=True),
    sa.Column('POS', sa.String(length=128), nullable=True),
    sa.Column('morph', sa.String(length=128), nullable=True),
    sa.Column('left_context', sa.String(length=512), nullable=True),
    sa.Column('right_context', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['corpus'], ['corpus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookmark',
    sa.Column('corpus_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['corpus_id'], ['corpus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['token_id'], ['word_token.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('corpus_id', 'user_id', 'token_id')
    )
    op.create_table('change_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('corpus', sa.Integer(), nullable=True),
    sa.Column('word_token_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('form', sa.String(length=128), nullable=True),
    sa.Column('lemma', sa.String(length=128), nullable=True),
    sa.Column('POS', sa.String(length=128), nullable=True),
    sa.Column('morph', sa.String(length=128), nullable=True),
    sa.Column('lemma_new', sa.String(length=128), nullable=True),
    sa.Column('POS_new', sa.String(length=128), nullable=True),
    sa.Column('morph_new', sa.String(length=128), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['corpus'], ['corpus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['word_token_id'], ['word_token.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('corpus', sa.Integer(), nullable=True),
    sa.Column('word_token_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.Enum('Addition', 'Deletion', 'Edition', name='types'), nullable=False),
    sa.Column('new', sa.String(length=100), nullable=True),
    sa.Column('old', sa.String(length=100), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['corpus'], ['corpus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['word_token_id'], ['word_token.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_history')
    op.drop_table('change_record')
    op.drop_table('bookmark')
    op.drop_table('word_token')
    op.drop_table('favorite')
    op.drop_table('corpus_user')
    op.drop_table('corpus_custom_dictionary')
    op.drop_table('control_lists_user')
    op.drop_table('column')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_last_name'))
        batch_op.drop_index(batch_op.f('ix_users_first_name'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('corpus')
    op.drop_table('allowed_pos')
    op.drop_table('allowed_morph')
    with op.batch_alter_table('allowed_lemma', schema=None) as batch_op:
        batch_op.drop_index('unique_label_per_control')

    op.drop_table('allowed_lemma')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_default'))

    op.drop_table('roles')
    op.drop_table('control_lists')
    # ### end Alembic commands ###
