"""Add controllist filter columns

Revision ID: 6888cf0e4db1
Revises: 5825ee1a86fe
Create Date: 2026-04-27 21:26:45.510423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6888cf0e4db1'
down_revision = '5825ee1a86fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('control_lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filter_punct', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('filter_numeral', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('filter_metadata', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('filter_ignore', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('control_lists', schema=None) as batch_op:
        batch_op.drop_column('filter_ignore')
        batch_op.drop_column('filter_metadata')
        batch_op.drop_column('filter_numeral')
        batch_op.drop_column('filter_punct')

    # ### end Alembic commands ###
