"""Add word_token corpus indexes

Revision ID: c3f233d4768e
Revises: 6888cf0e4db1
Create Date: 2026-04-27 21:26:58.732948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3f233d4768e'
down_revision = '6888cf0e4db1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word_token', schema=None) as batch_op:
        batch_op.create_index('ix_word_token_corpus_form', ['corpus', 'form'], unique=False)
        batch_op.create_index('ix_word_token_corpus_order', ['corpus', 'order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word_token', schema=None) as batch_op:
        batch_op.drop_index('ix_word_token_corpus_order')
        batch_op.drop_index('ix_word_token_corpus_form')

    # ### end Alembic commands ###
