from app.models import Corpus, WordToken, AllowedLemma, AllowedPOS, AllowedMorph, Column
from app.models import ControlLists, ControlListsUser


Floovant = Corpus(
    name="Floovant",
    id=2,
    control_lists_id=2
)
FloovantColumns = [
    Column(heading="Lemma", corpus_id=2),
    Column(heading="POS", corpus_id=2),
    Column(heading="Morph", corpus_id=2),
    Column(heading="Similar", corpus_id=2),
]
FCL = ControlLists(id=2, name="Floovant")
FloovantTokens = [
    WordToken(corpus=Floovant.id, form="SOIGNORS", lemma="seignor", left_context="", right_context="or escoutez que",
              label_uniform="seignor", morph="NOMB.=p|GENRE=m|CAS=n"),
    WordToken(corpus=Floovant.id, form="or", lemma="or4", left_context="SOIGNORS", right_context="escoutez que Dés",
              label_uniform="or4", morph="DEGRE=-"),
    WordToken(corpus=Floovant.id, form="escoutez", lemma="escouter", left_context="SOIGNORS or",
              right_context="que Dés vos", label_uniform="escouter", morph="MODE=imp|PERS.=2|NOMB.=p"),
    WordToken(corpus=Floovant.id, form="que", lemma="que4", left_context="SOIGNORS or escoutez",
              right_context="Dés vos soit", label_uniform="que4", morph="_"),
    WordToken(corpus=Floovant.id, form="Dés", lemma="dieu", left_context="or escoutez que",
              right_context="vos soit amis", label_uniform="dieu", morph="NOMB.=s|GENRE=m|CAS=n"),
    WordToken(corpus=Floovant.id, form="vos", lemma="vos1", left_context="escoutez que Dés",
              right_context="soit amis III", label_uniform="vos1", morph="PERS.=2|NOMB.=p|GENRE=m|CAS=r"),
    WordToken(corpus=Floovant.id, form="soit", lemma="estre1", left_context="que Dés vos",
              right_context="amis III vers", label_uniform="estre1", morph="MODE=sub|TEMPS=pst|PERS.=3|NOMB.=s"),
    WordToken(corpus=Floovant.id, form="amis", lemma="ami", left_context="Dés vos soit", right_context="III vers de",
              label_uniform="ami", morph="NOMB.=s|GENRE=m|CAS=n"),
    WordToken(corpus=Floovant.id, form="III", lemma="trois1", left_context="vos soit amis",
              right_context="vers de bone", label_uniform="trois1", morph="NOMB.=p|GENRE=m|CAS=r"),
    WordToken(corpus=Floovant.id, form="vers", lemma="vers1", left_context="soit amis III",
              right_context="de bone estoire", label_uniform="vers1", morph="NOMB.=p|GENRE=m|CAS=r"),
    WordToken(corpus=Floovant.id, form="de", lemma="de", left_context="amis III vers", right_context="bone estoire se",
              label_uniform="de", morph="_"),
    WordToken(corpus=Floovant.id, form="bone", lemma="bon", left_context="III vers de", right_context="estoire se je",
              label_uniform="bon", morph="NOMB.=s|GENRE=f|CAS=r|DEGRE=p"),
    WordToken(corpus=Floovant.id, form="estoire", lemma="estoire1", left_context="vers de bone",
              right_context="se je les", label_uniform="estoire1", morph="NOMB.=s|GENRE=f|CAS=r"),
    WordToken(corpus=Floovant.id, form="se", lemma="si", left_context="de bone estoire", right_context="je les vos",
              label_uniform="si", morph="DEGRE=-"),
    WordToken(corpus=Floovant.id, form="je", lemma="je", left_context="bone estoire se", right_context="les vos devis",
              label_uniform="je", morph="PERS.=1|NOMB.=s|GENRE=m|CAS=n"),
    WordToken(corpus=Floovant.id, form="les", lemma="il", left_context="estoire se je", right_context="vos devis Dou",
              label_uniform="il", morph="PERS.=3|NOMB.=p|GENRE=m|CAS=r"),
    WordToken(corpus=Floovant.id, form="vos", lemma="vos1", left_context="se je les", right_context="devis Dou premier",
              label_uniform="vos1", morph="PERS.=2|NOMB.=p|GENRE=m|CAS=r"),
    WordToken(corpus=Floovant.id, form="devis", lemma="deviser", left_context="je les vos",
              right_context="Dou premier roi", label_uniform="deviser", morph="MODE=ind|TEMPS=pst|PERS.=1|NOMB.=s"),
    WordToken(corpus=Floovant.id, form="Dou", lemma="de+le", left_context="les vos devis",
              right_context="premier roi de", label_uniform="de+le", morph="NOMB.=s|GENRE=m|CAS=r"),
    WordToken(corpus=Floovant.id, form="premier", lemma="premier", left_context="vos devis Dou",
              right_context="roi de France", label_uniform="premier", morph="NOMB.=s|GENRE=m|CAS=r"),
    WordToken(corpus=Floovant.id, form="roi", lemma="roi2", left_context="devis Dou premier",
              right_context="de France qui", label_uniform="roi2", morph="NOMB.=s|GENRE=m|CAS=r"),
    WordToken(corpus=Floovant.id, form="de", lemma="de", left_context="Dou premier roi",
              right_context="France qui crestïens", label_uniform="de", morph="_"),
    WordToken(corpus=Floovant.id, form="France", lemma="france", left_context="premier roi de",
              right_context="qui crestïens devint", label_uniform="france", morph="NOMB.=s|GENRE=f|CAS=r"),
    WordToken(corpus=Floovant.id, form="qui", lemma="qui", left_context="roi de France",
              right_context="crestïens devint Cil", label_uniform="qui", morph="NOMB.=s|GENRE=m|CAS=n"),
    WordToken(corpus=Floovant.id, form="crestïens", lemma="crestiien", left_context="de France qui",
              right_context="devint Cil ot", label_uniform="crestiien", morph="NOMB.=s|GENRE=m|CAS=n"),
    WordToken(corpus=Floovant.id, form="devint", lemma="devenir", left_context="France qui crestïens",
              right_context="Cil ot non", label_uniform="devenir", morph="MODE=ind|TEMPS=psp|PERS.=3|NOMB.=s"),
    WordToken(corpus=Floovant.id, form="Cil", lemma="cel", left_context="qui crestïens devint",
              right_context="ot non Cloovis", label_uniform="cel", morph="NOMB.=s|GENRE=m|CAS=n"),
    WordToken(corpus=Floovant.id, form="ot", lemma="avoir", left_context="crestïens devint Cil",
              right_context="non Cloovis si", label_uniform="avoir", morph="MODE=ind|TEMPS=psp|PERS.=3|NOMB.=s"),
    WordToken(corpus=Floovant.id, form="non", lemma="nom", left_context="devint Cil ot", right_context="Cloovis si com",
              label_uniform="nom", morph="NOMB.=s|GENRE=m|CAS=r"),
    WordToken(corpus=Floovant.id, form="Cloovis", lemma="clovis", left_context="Cil ot non",
              right_context="si com truis", label_uniform="clovis", morph="NOMB.=s|GENRE=m|CAS=r"),
    WordToken(corpus=Floovant.id, form="si", lemma="si", left_context="ot non Cloovis", right_context="com truis en",
              label_uniform="si", morph="DEGRE=-"),
    WordToken(corpus=Floovant.id, form="com", lemma="come1", left_context="non Cloovis si",
              right_context="truis en escrit", label_uniform="come1", morph="_"),
    WordToken(corpus=Floovant.id, form="truis", lemma="trover", left_context="Cloovis si com",
              right_context="en escrit", label_uniform="trover", morph="MODE=ind|TEMPS=pst|PERS.=1|NOMB.=s"),
    WordToken(corpus=Floovant.id, form="en", lemma="en1", left_context="si com truis", right_context="escrit",
              label_uniform="en1", morph="_"),
    WordToken(corpus=Floovant.id, form="escrit", lemma="escrit", left_context="com truis en", right_context="",
              label_uniform="escrit", morph="NOMB.=s|GENRE=m|CAS=r"),

]
FloovantAllowedPOS = [
    AllowedPOS(control_list=FCL.id, label="ADVgen"),
    AllowedPOS(control_list=FCL.id, label="VERcjg"),
    AllowedPOS(control_list=FCL.id, label="NOMcom"),
    AllowedPOS(control_list=FCL.id, label="ADJord"),
    AllowedPOS(control_list=FCL.id, label="ADJqua"),
    AllowedPOS(control_list=FCL.id, label="ADVneg"),
    AllowedPOS(control_list=FCL.id, label="CONsub"),
    AllowedPOS(control_list=FCL.id, label="DETcar"),
    AllowedPOS(control_list=FCL.id, label="NOMpro"),
    AllowedPOS(control_list=FCL.id, label="PRE"),
    AllowedPOS(control_list=FCL.id, label="PRE.DETdef"),
    AllowedPOS(control_list=FCL.id, label="PROdem"),
    AllowedPOS(control_list=FCL.id, label="PROper"),
    AllowedPOS(control_list=FCL.id, label="PROrel")
]
FloovantAllowedLemma = [
    AllowedLemma(control_list=FCL.id, label="escouter", label_uniform="escouter"),
    AllowedLemma(control_list=FCL.id, label="or4", label_uniform="or4"),
    AllowedLemma(control_list=FCL.id, label="seignor", label_uniform="seignor"),
    AllowedLemma(control_list=FCL.id, label="ami", label_uniform="ami"),
    AllowedLemma(control_list=FCL.id, label="avoir", label_uniform="avoir"),
    AllowedLemma(control_list=FCL.id, label="bon", label_uniform="bon"),
    AllowedLemma(control_list=FCL.id, label="cel", label_uniform="cel"),
    AllowedLemma(control_list=FCL.id, label="clovis", label_uniform="clovis"),
    AllowedLemma(control_list=FCL.id, label="come1", label_uniform="come1"),
    AllowedLemma(control_list=FCL.id, label="crestiien", label_uniform="crestiien"),
    AllowedLemma(control_list=FCL.id, label="de", label_uniform="de"),
    AllowedLemma(control_list=FCL.id, label="de+le", label_uniform="de+le"),
    AllowedLemma(control_list=FCL.id, label="devenir", label_uniform="devenir"),
    AllowedLemma(control_list=FCL.id, label="deviser", label_uniform="deviser"),
    AllowedLemma(control_list=FCL.id, label="dieu", label_uniform="dieu"),
    AllowedLemma(control_list=FCL.id, label="en1", label_uniform="en1"),
    AllowedLemma(control_list=FCL.id, label="escrit", label_uniform="escrit"),
    AllowedLemma(control_list=FCL.id, label="estoire1", label_uniform="estoire1"),
    AllowedLemma(control_list=FCL.id, label="estre1", label_uniform="estre1"),
    AllowedLemma(control_list=FCL.id, label="france", label_uniform="france"),
    AllowedLemma(control_list=FCL.id, label="il", label_uniform="il"),
    AllowedLemma(control_list=FCL.id, label="je", label_uniform="je"),
    AllowedLemma(control_list=FCL.id, label="nom", label_uniform="nom"),
    AllowedLemma(control_list=FCL.id, label="premier", label_uniform="premier"),
    AllowedLemma(control_list=FCL.id, label="que4", label_uniform="que4"),
    AllowedLemma(control_list=FCL.id, label="qui", label_uniform="qui"),
    AllowedLemma(control_list=FCL.id, label="roi2", label_uniform="roi2"),
    AllowedLemma(control_list=FCL.id, label="si", label_uniform="si"),
    AllowedLemma(control_list=FCL.id, label="trois1", label_uniform="trois1"),
    AllowedLemma(control_list=FCL.id, label="trover", label_uniform="trover"),
    AllowedLemma(control_list=FCL.id, label="vers1", label_uniform="vers1"),
    AllowedLemma(control_list=FCL.id, label="vos1", label_uniform="vos1")
]
FloovantAllowedMorph = [
    AllowedMorph(control_list=FCL.id, label="_", readable="pas de morphologie"),
    AllowedMorph(control_list=FCL.id, label="DEGRE=-", readable="non applicable"),
    AllowedMorph(control_list=FCL.id, label="MODE=imp|PERS.=2|NOMB.=p", readable="impératif 2e personne pluriel"),
    AllowedMorph(control_list=FCL.id, label="MODE=ind|TEMPS=psp|PERS.=3|NOMB.=s", readable="indicatif passé simple 3e personne singulier"),
    AllowedMorph(control_list=FCL.id, label="MODE=ind|TEMPS=pst|PERS.=1|NOMB.=s", readable="indicatif présent 1re personne singulier"),
    AllowedMorph(control_list=FCL.id, label="MODE=sub|TEMPS=pst|PERS.=3|NOMB.=s", readable="subjonctif présent 3e personne singulier"),
    AllowedMorph(control_list=FCL.id, label="NOMB.=p|GENRE=m|CAS=n", readable="pluriel masculin nominatif"),
    AllowedMorph(control_list=FCL.id, label="NOMB.=p|GENRE=m|CAS=r", readable="pluriel masculin régime"),
    AllowedMorph(control_list=FCL.id, label="NOMB.=s|GENRE=f|CAS=r", readable="singulier féminin régime"),
    AllowedMorph(control_list=FCL.id, label="NOMB.=s|GENRE=f|CAS=r|DEGRE=p", readable="singulier féminin régime positif"),
    AllowedMorph(control_list=FCL.id, label="NOMB.=s|GENRE=m|CAS=n", readable="singulier masculin nominatif"),
    AllowedMorph(control_list=FCL.id, label="NOMB.=s|GENRE=m|CAS=r", readable="singulier masculin régime"),
    AllowedMorph(control_list=FCL.id, label="PERS.=1|NOMB.=s|GENRE=m|CAS=n", readable="1re personne singulier masculin nominatif"),
    AllowedMorph(control_list=FCL.id, label="PERS.=2|NOMB.=p|GENRE=m|CAS=r", readable="2e personne pluriel masculin régime"),
    AllowedMorph(control_list=FCL.id, label="PERS.=3|NOMB.=p|GENRE=m|CAS=r", readable="3e personne pluriel masculin régime")
]
