from app.models import Corpus, WordToken, AllowedLemma, AllowedPOS, AllowedMorph, Column
from app.models import ControlLists, ControlListsUser

Wauchier = Corpus(
    name="Wauchier",
    id=1,
    control_lists_id=1
)
WauchierColumns = [
    Column(heading="Lemma", corpus_id=1),
    Column(heading="POS", corpus_id=1),
    Column(heading="Morph", corpus_id=1),
    Column(heading="Similar", corpus_id=1),
]
WCL = ControlLists(id=1, name="Wauchier")
WauchierTokens = [
    WordToken(corpus=Wauchier.id, form="De", lemma="de", POS="PRE", left_context="", right_context="seint Martin mout", label_uniform="de", morph="None"),
    WordToken(corpus=Wauchier.id, form="seint", lemma="saint", POS="ADJqua", left_context="De", right_context="Martin mout doit", label_uniform="saint", morph="None"),
    WordToken(corpus=Wauchier.id, form="Martin", lemma="martin", POS="NOMpro", left_context="De seint", right_context="mout doit on", label_uniform="martin", morph="None"),
    WordToken(corpus=Wauchier.id, form="mout", lemma="mout", POS="ADVgen", left_context="De seint Martin", right_context="doit on doucement", label_uniform="mout", morph="None"),
    WordToken(corpus=Wauchier.id, form="doit", lemma="devoir", POS="VERcjg", left_context="seint Martin mout", right_context="on doucement et", label_uniform="devoir", morph="None"),
    WordToken(corpus=Wauchier.id, form="on", lemma="un", POS="PRE", left_context="Martin mout doit", right_context="doucement et volentiers", label_uniform="un", morph="None"),
    WordToken(corpus=Wauchier.id, form="doucement", lemma="doucement", POS="ADVgen", left_context="mout doit on", right_context="et volentiers le", label_uniform="doucement", morph="None"),
    WordToken(corpus=Wauchier.id, form="et", lemma="et", POS="CONcoo", left_context="doit on doucement", right_context="volentiers le bien", label_uniform="et", morph="None"),
    WordToken(corpus=Wauchier.id, form="volentiers", lemma="volentiers", POS="ADVgen", left_context="on doucement et", right_context="le bien oïr", label_uniform="volentiers", morph="None"),
    WordToken(corpus=Wauchier.id, form="le", lemma="le", POS="DETdef", left_context="doucement et volentiers", right_context="bien oïr et", label_uniform="le", morph="None"),
    WordToken(corpus=Wauchier.id, form="bien", lemma="bien", POS="ADVgen", left_context="et volentiers le", right_context="oïr et entendre", label_uniform="bien", morph="None"),
    WordToken(corpus=Wauchier.id, form="oïr", lemma="öir", POS="VERinf", left_context="volentiers le bien", right_context="et entendre ,", label_uniform="oir", morph="None"),
    WordToken(corpus=Wauchier.id, form="et", lemma="et", POS="CONcoo", left_context="le bien oïr", right_context="entendre , car", label_uniform="et", morph="None"),
    WordToken(corpus=Wauchier.id, form="entendre", lemma="entendre", POS="VERinf", left_context="bien oïr et", right_context=", car par", label_uniform="entendre", morph="None"),
    WordToken(corpus=Wauchier.id, form=",", lemma=",", POS="PONfbl", left_context="oïr et entendre", right_context="car par le", label_uniform=",", morph="None"),
    WordToken(corpus=Wauchier.id, form="car", lemma="car", POS="CONcoo", left_context="et entendre ,", right_context="par le bien", label_uniform="car", morph="None"),
    WordToken(corpus=Wauchier.id, form="par", lemma="par", POS="PRE", left_context="entendre , car", right_context="le bien savoir", label_uniform="par", morph="None"),
    WordToken(corpus=Wauchier.id, form="le", lemma="le", POS="DETdef", left_context=", car par", right_context="bien savoir et", label_uniform="le", morph="None"),
    WordToken(corpus=Wauchier.id, form="bien", lemma="bien", POS="ADVgen", left_context="car par le", right_context="savoir et retenir", label_uniform="bien", morph="None"),
    WordToken(corpus=Wauchier.id, form="savoir", lemma="savoir", POS="VERinf", left_context="par le bien", right_context="et retenir puet", label_uniform="savoir", morph="None"),
    WordToken(corpus=Wauchier.id, form="et", lemma="et", POS="CONcoo", left_context="le bien savoir", right_context="retenir puet l", label_uniform="et", morph="None"),
    WordToken(corpus=Wauchier.id, form="retenir", lemma="retenir", POS="VERinf", left_context="bien savoir et", right_context="puet l en", label_uniform="retenir", morph="None"),
    WordToken(corpus=Wauchier.id, form="puet", lemma="pöoir", POS="VERcjg", left_context="savoir et retenir", right_context="l en sovent", label_uniform="pooir", morph="None"),
    WordToken(corpus=Wauchier.id, form="l", lemma="il", POS="PROper", left_context="et retenir puet", right_context="en sovent a", label_uniform="il", morph="None"),
    WordToken(corpus=Wauchier.id, form="en", lemma="en1", POS="PRE", left_context="retenir puet l", right_context="sovent a bien", label_uniform="en1", morph="None"),
    WordToken(corpus=Wauchier.id, form="sovent", lemma="savoir", POS="VERcjg", left_context="puet l en", right_context="a bien venir", label_uniform="savoir", morph="None"),
    WordToken(corpus=Wauchier.id, form="a", lemma="a", POS="PRE", left_context="l en sovent", right_context="bien venir .", label_uniform="a", morph="None"),
    WordToken(corpus=Wauchier.id, form="bien", lemma="bien", POS="ADVgen", left_context="en sovent a", right_context="venir . Qui", label_uniform="bien", morph="None"),
    WordToken(corpus=Wauchier.id, form="venir", lemma="venir", POS="VERinf", left_context="sovent a bien", right_context=". Qui bien", label_uniform="venir", morph="None"),
    WordToken(corpus=Wauchier.id, form=".", lemma=".", POS="PONfrt", left_context="a bien venir", right_context="Qui bien ne", label_uniform=".", morph="None"),
    WordToken(corpus=Wauchier.id, form="Qui", lemma="que2/3", POS="PROrel", left_context="bien venir .", right_context="bien ne seit", label_uniform="que2/3", morph="None"),
    WordToken(corpus=Wauchier.id, form="bien", lemma="bien", POS="ADVgen", left_context="venir . Qui", right_context="ne seit ne", label_uniform="bien", morph="None"),
    WordToken(corpus=Wauchier.id, form="ne", lemma="ne1", POS="ADVneg", left_context=". Qui bien", right_context="seit ne bien", label_uniform="ne1", morph="None"),
    WordToken(corpus=Wauchier.id, form="seit", lemma="estre1", POS="VERcjg", left_context="Qui bien ne", right_context="ne bien n", label_uniform="estre1", morph="None"),
    WordToken(corpus=Wauchier.id, form="ne", lemma="ne2", POS="CONcoo", left_context="bien ne seit", right_context="bien n entent", label_uniform="ne2", morph="None"),
    WordToken(corpus=Wauchier.id, form="bien", lemma="bien", POS="ADVgen", left_context="ne seit ne", right_context="n entent de", label_uniform="bien", morph="None"),
    WordToken(corpus=Wauchier.id, form="n", lemma="ne1", POS="ADVneg", left_context="seit ne bien", right_context="entent de bien", label_uniform="ne1", morph="None"),
    WordToken(corpus=Wauchier.id, form="entent", lemma="entendre", POS="VERcjg", left_context="ne bien n", right_context="de bien faire", label_uniform="entendre", morph="None"),
    WordToken(corpus=Wauchier.id, form="de", lemma="de", POS="PRE", left_context="bien n entent", right_context="bien faire n", label_uniform="de", morph="None"),
    WordToken(corpus=Wauchier.id, form="bien", lemma="bien", POS="ADVgen", left_context="n entent de", right_context="faire n a", label_uniform="bien", morph="None"),
    WordToken(corpus=Wauchier.id, form="faire", lemma="faire", POS="VERinf", left_context="entent de bien", right_context="n a nul", label_uniform="faire", morph="None"),
    WordToken(corpus=Wauchier.id, form="n", lemma="ne1", POS="ADVneg", left_context="de bien faire", right_context="a nul talent", label_uniform="ne1", morph="None"),
    WordToken(corpus=Wauchier.id, form="a", lemma="a", POS="PRE", left_context="bien faire n", right_context="nul talent .", label_uniform="a", morph="None"),
    WordToken(corpus=Wauchier.id, form="nul", lemma="nul", POS="DETind", left_context="faire n a", right_context="talent . Mes", label_uniform="nul", morph="None"),
    WordToken(corpus=Wauchier.id, form="talent", lemma="talent", POS="NOMcom", left_context="n a nul", right_context=". Mes del", label_uniform="talent", morph="None"),
    WordToken(corpus=Wauchier.id, form=".", lemma=".", POS="PONfrt", left_context="a nul talent", right_context="Mes del bien", label_uniform=".", morph="None"),
    WordToken(corpus=Wauchier.id, form="Mes", lemma="mais1", POS="CONcoo", left_context="nul talent .", right_context="del bien nest", label_uniform="mais1", morph="None"),
    WordToken(corpus=Wauchier.id, form="del", lemma="de", POS="PRE.DETdef", left_context="talent . Mes", right_context="bien nest sovent", label_uniform="de", morph="None"),
    WordToken(corpus=Wauchier.id, form="bien", lemma="bien", POS="ADVgen", left_context=". Mes del", right_context="nest sovent li", label_uniform="bien", morph="None"),
    WordToken(corpus=Wauchier.id, form="nest", lemma="naistre", POS="VERcjg", left_context="Mes del bien", right_context="sovent li biens", label_uniform="naistre", morph="None"),
    WordToken(corpus=Wauchier.id, form="sovent", lemma="savoir", POS="VERcjg", left_context="del bien nest", right_context="li biens ,", label_uniform="savoir", morph="None"),
    WordToken(corpus=Wauchier.id, form="li", lemma="le", POS="DETdef", left_context="bien nest sovent", right_context="biens , del", label_uniform="le", morph="None"),
    WordToken(corpus=Wauchier.id, form="biens", lemma="bien", POS="NOMcom", left_context="nest sovent li", right_context=", del mal", label_uniform="bien", morph="None"),
    WordToken(corpus=Wauchier.id, form=",", lemma=",", POS="PONfbl", left_context="sovent li biens", right_context="del mal li", label_uniform=",", morph="None"),
    WordToken(corpus=Wauchier.id, form="del", lemma="de", POS="PRE.DETdef", left_context="li biens ,", right_context="mal li maus", label_uniform="de", morph="None"),
    WordToken(corpus=Wauchier.id, form="mal", lemma="mal1", POS="NOMcom", left_context="biens , del", right_context="li maus si", label_uniform="mal1", morph="None"),
    WordToken(corpus=Wauchier.id, form="li", lemma="il", POS="PROper", left_context=", del mal", right_context="maus si com", label_uniform="il", morph="None"),
    WordToken(corpus=Wauchier.id, form="maus", lemma="mal1", POS="NOMcom", left_context="del mal li", right_context="si com dist", label_uniform="mal1", morph="None"),
    WordToken(corpus=Wauchier.id, form="si", lemma="si", POS="ADVgen", left_context="mal li maus", right_context="com dist l", label_uniform="si", morph="None"),
    WordToken(corpus=Wauchier.id, form="com", lemma="come1", POS="CONsub", left_context="li maus si", right_context="dist l Escriture", label_uniform="come1", morph="None"),
    WordToken(corpus=Wauchier.id, form="dist", lemma="dire", POS="VERcjg", left_context="maus si com", right_context="l Escriture .", label_uniform="dire", morph="None"),
    WordToken(corpus=Wauchier.id, form="l", lemma="le", POS="DETdef", left_context="si com dist", right_context="Escriture . Por", label_uniform="le", morph="None"),
    WordToken(corpus=Wauchier.id, form="Escriture", lemma="escrire", POS="NOMcom", left_context="com dist l", right_context=". Por ce", label_uniform="escrire", morph="None"),
    WordToken(corpus=Wauchier.id, form=".", lemma=".", POS="PONfrt", left_context="dist l Escriture", right_context="Por ce se", label_uniform=".", morph="None"),
    WordToken(corpus=Wauchier.id, form="Por", lemma="por2", POS="PRE", left_context="l Escriture .", right_context="ce se doit", label_uniform="por2", morph="None"),
    WordToken(corpus=Wauchier.id, form="ce", lemma="ce1", POS="PROdem", left_context="Escriture . Por", right_context="se doit l", label_uniform="ce1", morph="None"),
    WordToken(corpus=Wauchier.id, form="se", lemma="soi1", POS="PROper", left_context=". Por ce", right_context="doit l en", label_uniform="soi1", morph="None"),
    WordToken(corpus=Wauchier.id, form="doit", lemma="devoir", POS="VERcjg", left_context="Por ce se", right_context="l en au", label_uniform="devoir", morph="None"),
    WordToken(corpus=Wauchier.id, form="l", lemma="il", POS="PROper", left_context="ce se doit", right_context="en au bien", label_uniform="il", morph="None"),
    WordToken(corpus=Wauchier.id, form="en", lemma="en1", POS="PRE", left_context="se doit l", right_context="au bien avoier", label_uniform="en1", morph="None"),
    WordToken(corpus=Wauchier.id, form="au", lemma="a", POS="PRE.DETdef", left_context="doit l en", right_context="bien avoier et", label_uniform="a", morph="None"),
    WordToken(corpus=Wauchier.id, form="bien", lemma="bien", POS="ADVgen", left_context="l en au", right_context="avoier et le", label_uniform="bien", morph="None"),
    WordToken(corpus=Wauchier.id, form="avoier", lemma="avoir", POS="VERinf", left_context="en au bien", right_context="et le bien", label_uniform="avoir", morph="None"),
    WordToken(corpus=Wauchier.id, form="et", lemma="et", POS="CONcoo", left_context="au bien avoier", right_context="le bien feire", label_uniform="et", morph="None"),
    WordToken(corpus=Wauchier.id, form="le", lemma="le", POS="DETdef", left_context="bien avoier et", right_context="bien feire ,", label_uniform="le", morph="None"),
    WordToken(corpus=Wauchier.id, form="bien", lemma="bien", POS="ADVgen", left_context="avoier et le", right_context="feire , si", label_uniform="bien", morph="None"),
    WordToken(corpus=Wauchier.id, form="feire", lemma="faire", POS="VERinf", left_context="et le bien", right_context=", si com", label_uniform="faire", morph="None"),
    WordToken(corpus=Wauchier.id, form=",", lemma=",", POS="PONfbl", left_context="le bien feire", right_context="si com li", label_uniform=",", morph="None"),
    WordToken(corpus=Wauchier.id, form="si", lemma="si", POS="ADVgen", left_context="bien feire ,", right_context="com li seint", label_uniform="si", morph="None"),
    WordToken(corpus=Wauchier.id, form="com", lemma="come1", POS="CONsub", left_context="feire , si", right_context="li seint home", label_uniform="come1", morph="None"),
    WordToken(corpus=Wauchier.id, form="li", lemma="le", POS="PROper", left_context=", si com", right_context="seint home firent", label_uniform="le", morph="None"),
    WordToken(corpus=Wauchier.id, form="seint", lemma="saint", POS="VERcjg", left_context="si com li", right_context="home firent ça", label_uniform="saint", morph="None"),
    WordToken(corpus=Wauchier.id, form="home", lemma="ome", POS="NOMcom", left_context="com li seint", right_context="firent ça en", label_uniform="ome", morph="None"),
    WordToken(corpus=Wauchier.id, form="firent", lemma="faire", POS="VERcjg", left_context="li seint home", right_context="ça en arriere", label_uniform="faire", morph="None"),
    WordToken(corpus=Wauchier.id, form="ça", lemma="ça", POS="ADVgen", left_context="seint home firent", right_context="en arriere de", label_uniform="ca", morph="None"),
    WordToken(corpus=Wauchier.id, form="en", lemma="en1", POS="PRE", left_context="home firent ça", right_context="arriere de cui", label_uniform="en1", morph="None"),
    WordToken(corpus=Wauchier.id, form="arriere", lemma="ariere", POS="ADVgen", left_context="firent ça en", right_context="de cui nos", label_uniform="ariere", morph="None"),
    WordToken(corpus=Wauchier.id, form="de", lemma="de", POS="PRE", left_context="ça en arriere", right_context="cui nos trovons", label_uniform="de", morph="None"),
    WordToken(corpus=Wauchier.id, form="cui", lemma="que2/3", POS="PROrel", left_context="en arriere de", right_context="nos trovons les", label_uniform="que2/3", morph="None"),
    WordToken(corpus=Wauchier.id, form="nos", lemma="nos1", POS="PROper", left_context="arriere de cui", right_context="trovons les oevres", label_uniform="nos1", morph="None"),
    WordToken(corpus=Wauchier.id, form="trovons", lemma="trover", POS="VERcjg", left_context="de cui nos", right_context="les oevres et", label_uniform="trover", morph="None"),
    WordToken(corpus=Wauchier.id, form="les", lemma="le", POS="DETdef", left_context="cui nos trovons", right_context="", label_uniform="le", morph="None"),
    WordToken(corpus=Wauchier.id, form="oevres", lemma="uevre", POS="NOMcom", left_context="nos trovons les", right_context="et les vies", label_uniform="uevre", morph="None"),
    WordToken(corpus=Wauchier.id, form="et", lemma="et", POS="CONcoo", left_context="trovons les oevres", right_context="les vies escriptures", label_uniform="et", morph="None"),
    WordToken(corpus=Wauchier.id, form="les", lemma="le", POS="DETdef", left_context="", right_context="vies escriptures .", label_uniform="le", morph="None"),
    WordToken(corpus=Wauchier.id, form="vies", lemma="vie", POS="NOMcom", left_context="oevres et les", right_context="escriptures . Et", label_uniform="vie", morph="None"),
    WordToken(corpus=Wauchier.id, form="escriptures", lemma="escrever", POS="VERppe", left_context="et les vies", right_context=". Et bien", label_uniform="escrever", morph="None"),
    WordToken(corpus=Wauchier.id, form=".", lemma=".", POS="PONfrt", left_context="les vies escriptures", right_context="Et bien sacent", label_uniform=".", morph="None"),
    WordToken(corpus=Wauchier.id, form="Et", lemma="et", POS="CONcoo", left_context="vies escriptures .", right_context="bien sacent tuit", label_uniform="et", morph="None"),
    WordToken(corpus=Wauchier.id, form="bien", lemma="bien", POS="ADVgen", left_context="escriptures . Et", right_context="sacent tuit cil", label_uniform="bien", morph="None"),
    WordToken(corpus=Wauchier.id, form="sacent", lemma="savoir", POS="VERcjg", left_context=". Et bien", right_context="tuit cil qi", label_uniform="savoir", morph="None"),
    WordToken(corpus=Wauchier.id, form="tuit", lemma="tot", POS="DETind", left_context="Et bien sacent", right_context="cil qi vivent", label_uniform="tot", morph="None"),
    WordToken(corpus=Wauchier.id, form="cil", lemma="cel", POS="PROdem", left_context="bien sacent tuit", right_context="qi vivent qe", label_uniform="cel", morph="None"),
    WordToken(corpus=Wauchier.id, form="qi", lemma="ci", POS="PROper", left_context="sacent tuit cil", right_context="vivent qe ja", label_uniform="ci", morph="None"),
    WordToken(corpus=Wauchier.id, form="vivent", lemma="vëoir", POS="VERcjg", left_context="tuit cil qi", right_context="qe ja n", label_uniform="veoir", morph="None"),
    WordToken(corpus=Wauchier.id, form="qe", lemma="ce1", POS="PROdem", left_context="cil qi vivent", right_context="ja n auront", label_uniform="ce1", morph="None"),
    WordToken(corpus=Wauchier.id, form="ja", lemma="ja", POS="ADVgen", left_context="qi vivent qe", right_context="n auront tant", label_uniform="ja", morph="None"),
    WordToken(corpus=Wauchier.id, form="n", lemma="ne1", POS="ADVneg", left_context="vivent qe ja", right_context="auront tant de", label_uniform="ne1", morph="None"),
    WordToken(corpus=Wauchier.id, form="auront", lemma="aucun", POS="VERcjg", left_context="qe ja n", right_context="tant de bien", label_uniform="aucun", morph="None"),
    WordToken(corpus=Wauchier.id, form="tant", lemma="tant", POS="ADVgen", left_context="ja n auront", right_context="de bien fet", label_uniform="tant", morph="None"),
    WordToken(corpus=Wauchier.id, form="de", lemma="de", POS="PRE", left_context="n auront tant", right_context="bien fet en", label_uniform="de", morph="None"),
    WordToken(corpus=Wauchier.id, form="bien", lemma="bien", POS="ADVgen", left_context="auront tant de", right_context="fet en totes", label_uniform="bien", morph="None"),
    WordToken(corpus=Wauchier.id, form="fet", lemma="faire", POS="VERppe", left_context="tant de bien", right_context="en totes lor", label_uniform="faire", morph="None"),
    WordToken(corpus=Wauchier.id, form="en", lemma="en1", POS="PRE", left_context="de bien fet", right_context="totes lor vies", label_uniform="en1", morph="None"),
    WordToken(corpus=Wauchier.id, form="totes", lemma="tot", POS="DETind", left_context="bien fet en", right_context="lor vies qe", label_uniform="tot", morph="None"),
    WordToken(corpus=Wauchier.id, form="lor", lemma="lor2", POS="DETpos", left_context="fet en totes", right_context="vies qe qant", label_uniform="lor2", morph="None"),
    WordToken(corpus=Wauchier.id, form="vies", lemma="vie", POS="NOMcom", left_context="en totes lor", right_context="qe qant la", label_uniform="vie", morph="None"),
    WordToken(corpus=Wauchier.id, form="qe", lemma="ce1", POS="PROdem", left_context="totes lor vies", right_context="qant la mort", label_uniform="ce1", morph="None"),
    WordToken(corpus=Wauchier.id, form="qant", lemma="cant1", POS="CONsub", left_context="lor vies qe", right_context="la mort dont", label_uniform="cant1", morph="None"),
    WordToken(corpus=Wauchier.id, form="la", lemma="le", POS="DETdef", left_context="vies qe qant", right_context="mort dont nule", label_uniform="le", morph="None"),
    WordToken(corpus=Wauchier.id, form="mort", lemma="mort", POS="NOMcom", left_context="qe qant la", right_context="dont nule rien", label_uniform="mort", morph="None"),
    WordToken(corpus=Wauchier.id, form="dont", lemma="dont", POS="PROrel", left_context="qant la mort", right_context="nule rien n", label_uniform="dont", morph="None"),
    WordToken(corpus=Wauchier.id, form="nule", lemma="nul", POS="DETind", left_context="la mort dont", right_context="rien n eschape", label_uniform="nul", morph="None"),
    WordToken(corpus=Wauchier.id, form="rien", lemma="rien", POS="NOMcom", left_context="mort dont nule", right_context="n eschape les", label_uniform="rien", morph="None"),
    WordToken(corpus=Wauchier.id, form="n", lemma="ne1", POS="ADVneg", left_context="dont nule rien", right_context="eschape les poindera", label_uniform="ne1", morph="None"),
    WordToken(corpus=Wauchier.id, form="eschape", lemma="eschaper", POS="VERcjg", left_context="nule rien n", right_context="les poindera au", label_uniform="eschaper", morph="None"),
    WordToken(corpus=Wauchier.id, form="les", lemma="le", POS="DETdef", left_context="rien n eschape", right_context="poindera au cuer", label_uniform="le", morph="None"),
    WordToken(corpus=Wauchier.id, form="poindera", lemma="poindre", POS="VERcjg", left_context="n eschape les", right_context="au cuer q", label_uniform="poindre", morph="None"),
    WordToken(corpus=Wauchier.id, form="au", lemma="a", POS="PRE.DETdef", left_context="eschape les poindera", right_context="cuer q il", label_uniform="a", morph="None"),
    WordToken(corpus=Wauchier.id, form="cuer", lemma="cuer2", POS="NOMcom", left_context="les poindera au", right_context="q il ne", label_uniform="cuer2", morph="None"),
    WordToken(corpus=Wauchier.id, form="q", lemma=":", POS="PONfrt", left_context="poindera au cuer", right_context="il ne cuident", label_uniform=":", morph="None"),
    WordToken(corpus=Wauchier.id, form="il", lemma="il", POS="PROper", left_context="au cuer q", right_context="ne cuident petit", label_uniform="il", morph="None"),
    WordToken(corpus=Wauchier.id, form="ne", lemma="ne1", POS="ADVneg", left_context="cuer q il", right_context="cuident petit avoir", label_uniform="ne1", morph="None"),
    WordToken(corpus=Wauchier.id, form="cuident", lemma="cuidier", POS="VERcjg", left_context="q il ne", right_context="petit avoir fait", label_uniform="cuidier", morph="None"),
    WordToken(corpus=Wauchier.id, form="petit", lemma="petit", POS="ADJqua", left_context="il ne cuident", right_context="avoir fait .", label_uniform="petit", morph="None"),
    WordToken(corpus=Wauchier.id, form="avoir", lemma="avoir", POS="VERinf", left_context="ne cuident petit", right_context="fait . Dex", label_uniform="avoir", morph="None"),
    WordToken(corpus=Wauchier.id, form="fait", lemma="faire", POS="VERppe", left_context="cuident petit avoir", right_context=". Dex !", label_uniform="faire", morph="None"),
    WordToken(corpus=Wauchier.id, form=".", lemma=".", POS="PONfrt", left_context="petit avoir fait", right_context="Dex ! Qe", label_uniform=".", morph="None"),
    WordToken(corpus=Wauchier.id, form="Dex", lemma="dieu", POS="NOMpro", left_context="avoir fait .", right_context="! Qe feront", label_uniform="dieu", morph="None"),
    WordToken(corpus=Wauchier.id, form="!", lemma="!", POS="PONfrt", left_context="fait . Dex", right_context="Qe feront dont", label_uniform="!", morph="None"),
    WordToken(corpus=Wauchier.id, form="Qe", lemma="ce1", POS="PROdem", left_context=". Dex !", right_context="feront dont cil", label_uniform="ce1", morph="None"),
    WordToken(corpus=Wauchier.id, form="feront", lemma="faire", POS="VERcjg", left_context="Dex ! Qe", right_context="dont cil qui", label_uniform="faire", morph="None"),
    WordToken(corpus=Wauchier.id, form="dont", lemma="dont", POS="PROrel", left_context="! Qe feront", right_context="cil qui riche", label_uniform="dont", morph="None"),
    WordToken(corpus=Wauchier.id, form="cil", lemma="cel", POS="PROdem", left_context="Qe feront dont", right_context="qui riche sont", label_uniform="cel", morph="None"),
    WordToken(corpus=Wauchier.id, form="qui", lemma="que2/3", POS="PROrel", left_context="feront dont cil", right_context="riche sont et", label_uniform="que2/3", morph="None"),
    WordToken(corpus=Wauchier.id, form="riche", lemma="riche", POS="ADJqua", left_context="dont cil qui", right_context="sont et aise", label_uniform="riche", morph="None"),
    WordToken(corpus=Wauchier.id, form="sont", lemma="estre1", POS="VERcjg", left_context="cil qui riche", right_context="et aise de", label_uniform="estre1", morph="None"),
    WordToken(corpus=Wauchier.id, form="et", lemma="et", POS="CONcoo", left_context="qui riche sont", right_context="aise de l", label_uniform="et", morph="None"),
    WordToken(corpus=Wauchier.id, form="aise", lemma="aise", POS="NOMcom", left_context="riche sont et", right_context="de l avoir", label_uniform="aise", morph="None"),
    WordToken(corpus=Wauchier.id, form="de", lemma="de", POS="PRE", left_context="sont et aise", right_context="", label_uniform="de", morph="None"),
    WordToken(corpus=Wauchier.id, form="l", lemma="le", POS="DETdef", left_context="et aise de", right_context="avoir de cest", label_uniform="le", morph="None"),
    WordToken(corpus=Wauchier.id, form="avoir", lemma="avoir", POS="VERinf", left_context="aise de l", right_context="de cest siecle", label_uniform="avoir", morph="None"),
    WordToken(corpus=Wauchier.id, form="de", lemma="de", POS="PRE", left_context="", right_context="cest siecle ,", label_uniform="de", morph="None"),
    WordToken(corpus=Wauchier.id, form="cest", lemma="cest", POS="DETdem", left_context="l avoir de", right_context="siecle , ne", label_uniform="cest", morph="None"),
    WordToken(corpus=Wauchier.id, form="siecle", lemma="siecle", POS="NOMcom", left_context="avoir de cest", right_context=", ne en", label_uniform="siecle", morph="None"),
    WordToken(corpus=Wauchier.id, form=",", lemma=",", POS="PONfbl", left_context="de cest siecle", right_context="ne en eus", label_uniform=",", morph="None"),
    WordToken(corpus=Wauchier.id, form="ne", lemma="ne2", POS="CONcoo", left_context="cest siecle ,", right_context="en eus n", label_uniform="ne2", morph="None"),
    WordToken(corpus=Wauchier.id, form="en", lemma="en2", POS="PROadv", left_context="siecle , ne", right_context="eus n ont", label_uniform="en2", morph="None"),
    WordToken(corpus=Wauchier.id, form="eus", lemma="estre1", POS="VERcjg", left_context=", ne en", right_context="n ont douçor", label_uniform="estre1", morph="None"),
    WordToken(corpus=Wauchier.id, form="n", lemma="ne1", POS="ADVneg", left_context="ne en eus", right_context="ont douçor ne", label_uniform="ne1", morph="None"),
    WordToken(corpus=Wauchier.id, form="ont", lemma="avoir", POS="VERcjg", left_context="en eus n", right_context="douçor ne humilité", label_uniform="avoir", morph="None"),
    WordToken(corpus=Wauchier.id, form="douçor", lemma="douçor", POS="NOMcom", left_context="eus n ont", right_context="ne humilité ne", label_uniform="doucor", morph="None"),
    WordToken(corpus=Wauchier.id, form="ne", lemma="ne2", POS="CONcoo", left_context="n ont douçor", right_context="humilité ne misericorde", label_uniform="ne2", morph="None"),
    WordToken(corpus=Wauchier.id, form="humilité", lemma="umelité", POS="NOMcom", left_context="ont douçor ne", right_context="ne misericorde ,", label_uniform="umelite", morph="None"),
    WordToken(corpus=Wauchier.id, form="ne", lemma="ne2", POS="CONcoo", left_context="douçor ne humilité", right_context="misericorde , ainz", label_uniform="ne2", morph="None"),
    WordToken(corpus=Wauchier.id, form="misericorde", lemma="misericorde", POS="NOMcom", left_context="ne humilité ne", right_context=", ainz sont", label_uniform="misericorde", morph="None"),
    WordToken(corpus=Wauchier.id, form=",", lemma=",", POS="PONfbl", left_context="humilité ne misericorde", right_context="ainz sont plein", label_uniform=",", morph="None"),
    WordToken(corpus=Wauchier.id, form="ainz", lemma="ainz", POS="ADVgen", left_context="ne misericorde ,", right_context="sont plein d", label_uniform="ainz", morph="None"),
    WordToken(corpus=Wauchier.id, form="sont", lemma="estre1", POS="VERcjg", left_context="misericorde , ainz", right_context="plein d angoisse", label_uniform="estre1", morph="None"),
    WordToken(corpus=Wauchier.id, form="plein", lemma="plein", POS="ADJqua", left_context=", ainz sont", right_context="d angoisse et", label_uniform="plein", morph="None"),
    WordToken(corpus=Wauchier.id, form="d", lemma="de", POS="PRE", left_context="ainz sont plein", right_context="angoisse et de", label_uniform="de", morph="None"),
    WordToken(corpus=Wauchier.id, form="angoisse", lemma="angoisse", POS="NOMcom", left_context="sont plein d", right_context="et de traïsson", label_uniform="angoisse", morph="None"),
    WordToken(corpus=Wauchier.id, form="et", lemma="et", POS="CONcoo", left_context="plein d angoisse", right_context="", label_uniform="et", morph="None"),
    WordToken(corpus=Wauchier.id, form="de", lemma="de", POS="PRE", left_context="d angoisse et", right_context="", label_uniform="de", morph="None"),
    WordToken(corpus=Wauchier.id, form="traïsson", lemma="träir", POS="NOMcom", left_context="angoisse et de", right_context="et de felonie", label_uniform="trair", morph="None"),
    WordToken(corpus=Wauchier.id, form="et", lemma="et", POS="CONcoo", left_context="", right_context="de felonie et", label_uniform="et", morph="None"),
    WordToken(corpus=Wauchier.id, form="de", lemma="de", POS="PRE", left_context="", right_context="felonie et de", label_uniform="de", morph="None"),
    WordToken(corpus=Wauchier.id, form="felonie", lemma="felonie", POS="NOMcom", left_context="traïsson et de", right_context="et de si", label_uniform="felonie", morph="None"),
    WordToken(corpus=Wauchier.id, form="et", lemma="et", POS="CONcoo", left_context="", right_context="de si grant", label_uniform="et", morph="None"),
    WordToken(corpus=Wauchier.id, form="de", lemma="de", POS="PRE", left_context="", right_context="si grant avarice", label_uniform="de", morph="None"),
    WordToken(corpus=Wauchier.id, form="si", lemma="si", POS="ADVgen", left_context="felonie et de", right_context="grant avarice qe", label_uniform="si", morph="None"),
    WordToken(corpus=Wauchier.id, form="grant", lemma="grant", POS="ADJqua", left_context="et de si", right_context="avarice qe com", label_uniform="grant", morph="None"),
    WordToken(corpus=Wauchier.id, form="avarice", lemma="aparler", POS="NOMcom", left_context="de si grant", right_context="qe com plus", label_uniform="aparler", morph="None"),
    WordToken(corpus=Wauchier.id, form="qe", lemma="ce1", POS="PROper", left_context="si grant avarice", right_context="com plus ont", label_uniform="ce1", morph="None"),
    WordToken(corpus=Wauchier.id, form="com", lemma="come1", POS="CONsub", left_context="grant avarice qe", right_context="plus ont richesces", label_uniform="come1", morph="None"),
    WordToken(corpus=Wauchier.id, form="plus", lemma="plus", POS="ADVgen", left_context="avarice qe com", right_context="ont richesces et", label_uniform="plus", morph="None"),
    WordToken(corpus=Wauchier.id, form="ont", lemma="avoir", POS="VERcjg", left_context="qe com plus", right_context="richesces et avoirs", label_uniform="avoir", morph="None"),
    WordToken(corpus=Wauchier.id, form="richesces", lemma="richece", POS="NOMcom", left_context="com plus ont", right_context="et avoirs ,", label_uniform="richece", morph="None"),
    WordToken(corpus=Wauchier.id, form="et", lemma="et", POS="CONcoo", left_context="plus ont richesces", right_context="avoirs , plus", label_uniform="et", morph="None"),
    WordToken(corpus=Wauchier.id, form="avoirs", lemma="avoir", POS="VERinf", left_context="ont richesces et", right_context=", plus en", label_uniform="avoir", morph="None"),
    WordToken(corpus=Wauchier.id, form=",", lemma=",", POS="PONfbl", left_context="richesces et avoirs", right_context="plus en desirrent", label_uniform=",", morph="None"),
    WordToken(corpus=Wauchier.id, form="plus", lemma="plus", POS="ADVgen", left_context="et avoirs ,", right_context="en desirrent a", label_uniform="plus", morph="None"),
    WordToken(corpus=Wauchier.id, form="en", lemma="en2", POS="PROadv", left_context="avoirs , plus", right_context="desirrent a avoir", label_uniform="en2", morph="None"),
    WordToken(corpus=Wauchier.id, form="desirrent", lemma="desirrer", POS="VERcjg", left_context=", plus en", right_context="a avoir ?", label_uniform="desirrer", morph="None"),
    WordToken(corpus=Wauchier.id, form="a", lemma="a", POS="PRE", left_context="plus en desirrent", right_context="avoir ? Ce", label_uniform="a", morph="None"),
    WordToken(corpus=Wauchier.id, form="avoir", lemma="avoir", POS="VERinf", left_context="en desirrent a", right_context="? Ce fet", label_uniform="avoir", morph="None"),
    WordToken(corpus=Wauchier.id, form="?", lemma="?", POS="PONfrt", left_context="desirrent a avoir", right_context="Ce fet li", label_uniform="?", morph="None"),
    WordToken(corpus=Wauchier.id, form="Ce", lemma="ce1", POS="PROdem", left_context="a avoir ?", right_context="fet li deables", label_uniform="ce1", morph="None"),
    WordToken(corpus=Wauchier.id, form="fet", lemma="faire", POS="VERcjg", left_context="avoir ? Ce", right_context="li deables qi", label_uniform="faire", morph="None"),
    WordToken(corpus=Wauchier.id, form="li", lemma="le", POS="DETdef", left_context="? Ce fet", right_context="deables qi en", label_uniform="le", morph="None"),
    WordToken(corpus=Wauchier.id, form="deables", lemma="dïable", POS="NOMcom", left_context="Ce fet li", right_context="qi en tel", label_uniform="diable", morph="None"),
    WordToken(corpus=Wauchier.id, form="qi", lemma="un", POS="ADVgen", left_context="fet li deables", right_context="en tel maniere", label_uniform="un", morph="None"),
    WordToken(corpus=Wauchier.id, form="en", lemma="en1", POS="PRE", left_context="li deables qi", right_context="tel maniere les", label_uniform="en1", morph="None"),
    WordToken(corpus=Wauchier.id, form="tel", lemma="tel", POS="DETind", left_context="deables qi en", right_context="maniere les a", label_uniform="tel", morph="None"),
    WordToken(corpus=Wauchier.id, form="maniere", lemma="maniere", POS="NOMcom", left_context="qi en tel", right_context="les a laciez", label_uniform="maniere", morph="None"),
    WordToken(corpus=Wauchier.id, form="les", lemma="il", POS="PROper", left_context="en tel maniere", right_context="a laciez et", label_uniform="il", morph="None"),
    WordToken(corpus=Wauchier.id, form="a", lemma="a", POS="VERcjg", left_context="tel maniere les", right_context="laciez et pris", label_uniform="a", morph="None"),
    WordToken(corpus=Wauchier.id, form="laciez", lemma="lacier", POS="VERppe", left_context="maniere les a", right_context="et pris q", label_uniform="lacier", morph="None"),
    WordToken(corpus=Wauchier.id, form="et", lemma="et", POS="CONcoo", left_context="les a laciez", right_context="pris q il", label_uniform="et", morph="None"),
    WordToken(corpus=Wauchier.id, form="pris", lemma="prendre", POS="VERppe", left_context="a laciez et", right_context="q il les", label_uniform="prendre", morph="None"),
    WordToken(corpus=Wauchier.id, form="q", lemma=":", POS="PONfrt", left_context="laciez et pris", right_context="il les enmeine", label_uniform=":", morph="None"),
    WordToken(corpus=Wauchier.id, form="il", lemma="il", POS="PROper", left_context="et pris q", right_context="les enmeine en", label_uniform="il", morph="None"),
    WordToken(corpus=Wauchier.id, form="les", lemma="il", POS="PROper", left_context="pris q il", right_context="enmeine en infer", label_uniform="il", morph="None"),
    WordToken(corpus=Wauchier.id, form="enmeine", lemma="enoiier", POS="VERcjg", left_context="q il les", right_context="en infer le", label_uniform="enoiier", morph="None"),
    WordToken(corpus=Wauchier.id, form="en", lemma="en2", POS="PROadv", left_context="il les enmeine", right_context="infer le grant", label_uniform="en2", morph="None"),
    WordToken(corpus=Wauchier.id, form="infer", lemma="inde", POS="VERinf", left_context="les enmeine en", right_context="le grant chemin", label_uniform="inde", morph="None"),
    WordToken(corpus=Wauchier.id, form="le", lemma="le", POS="DETdef", left_context="enmeine en infer", right_context="grant chemin plenier", label_uniform="le", morph="None"),
    WordToken(corpus=Wauchier.id, form="grant", lemma="grant", POS="ADJqua", left_context="en infer le", right_context="chemin plenier .", label_uniform="grant", morph="None"),
    WordToken(corpus=Wauchier.id, form="chemin", lemma="chemin", POS="NOMcom", left_context="infer le grant", right_context="plenier . De", label_uniform="chemin", morph="None"),
    WordToken(corpus=Wauchier.id, form="plenier", lemma="plenier2", POS="VERinf", left_context="le grant chemin", right_context=". De ce", label_uniform="plenier2", morph="None"),
    WordToken(corpus=Wauchier.id, form=".", lemma=".", POS="PONfrt", left_context="grant chemin plenier", right_context="De ce se", label_uniform=".", morph="None"),
    WordToken(corpus=Wauchier.id, form="De", lemma="de", POS="PRE", left_context="chemin plenier .", right_context="ce se gardent", label_uniform="de", morph="None"),
    WordToken(corpus=Wauchier.id, form="ce", lemma="ce1", POS="PROdem", left_context="plenier . De", right_context="se gardent li", label_uniform="ce1", morph="None"),
    WordToken(corpus=Wauchier.id, form="se", lemma="soi1", POS="PROper", left_context=". De ce", right_context="gardent li seint", label_uniform="soi1", morph="None"),
    WordToken(corpus=Wauchier.id, form="gardent", lemma="garder", POS="VERcjg", left_context="De ce se", right_context="li seint home", label_uniform="garder", morph="None"),
    WordToken(corpus=Wauchier.id, form="li", lemma="le", POS="PROper", left_context="ce se gardent", right_context="seint home qi", label_uniform="le", morph="None"),
    WordToken(corpus=Wauchier.id, form="seint", lemma="saint", POS="VERcjg", left_context="se gardent li", right_context="home qi par", label_uniform="saint", morph="None"),
    WordToken(corpus=Wauchier.id, form="home", lemma="ome", POS="NOMcom", left_context="gardent li seint", right_context="qi par dolereuses", label_uniform="ome", morph="None"),
    WordToken(corpus=Wauchier.id, form="qi", lemma="ci", POS="ADVgen", left_context="li seint home", right_context="par dolereuses peinnes", label_uniform="ci", morph="None"),
    WordToken(corpus=Wauchier.id, form="par", lemma="par", POS="PRE", left_context="seint home qi", right_context="dolereuses peinnes et", label_uniform="par", morph="None"),
    WordToken(corpus=Wauchier.id, form="dolereuses", lemma="doloros", POS="ADJqua", left_context="home qi par", right_context="peinnes et par", label_uniform="doloros", morph="None"),
    WordToken(corpus=Wauchier.id, form="peinnes", lemma="peine", POS="NOMcom", left_context="qi par dolereuses", right_context="et par griez", label_uniform="peine", morph="None"),
    WordToken(corpus=Wauchier.id, form="et", lemma="et", POS="CONcoo", left_context="par dolereuses peinnes", right_context="par griez tormenz", label_uniform="et", morph="None"),
    WordToken(corpus=Wauchier.id, form="par", lemma="par", POS="PRE", left_context="dolereuses peinnes et", right_context="griez tormenz et", label_uniform="par", morph="None"),
    WordToken(corpus=Wauchier.id, form="griez", lemma="grief", POS="ADJqua", left_context="peinnes et par", right_context="tormenz et par", label_uniform="grief", morph="None"),
    WordToken(corpus=Wauchier.id, form="tormenz", lemma="tornëiz", POS="VERppe", left_context="et par griez", right_context="et par veilles", label_uniform="torneiz", morph="None"),
    WordToken(corpus=Wauchier.id, form="et", lemma="et", POS="CONcoo", left_context="par griez tormenz", right_context="", label_uniform="et", morph="None"),
    WordToken(corpus=Wauchier.id, form="par", lemma="par", POS="PRE", left_context="griez tormenz et", right_context="", label_uniform="par", morph="None"),
    WordToken(corpus=Wauchier.id, form="veilles", lemma="veillier2", POS="NOMcom", left_context="tormenz et par", right_context="et par geunes", label_uniform="veillier2", morph="None"),
    WordToken(corpus=Wauchier.id, form="et", lemma="et", POS="CONcoo", left_context="", right_context="par geunes et", label_uniform="et", morph="None"),
    WordToken(corpus=Wauchier.id, form="par", lemma="par", POS="PRE", left_context="", right_context="geunes et par", label_uniform="par", morph="None"),
    WordToken(corpus=Wauchier.id, form="geunes", lemma="jëuner", POS="NOMcom", left_context="veilles et par", right_context="et par toutes", label_uniform="jeuner", morph="None"),
    WordToken(corpus=Wauchier.id, form="et", lemma="et", POS="CONcoo", left_context="", right_context="par toutes bones", label_uniform="et", morph="None"),
    WordToken(corpus=Wauchier.id, form="par", lemma="par", POS="PRE", left_context="", right_context="toutes bones oevres", label_uniform="par", morph="None"),
    WordToken(corpus=Wauchier.id, form="toutes", lemma="tort1", POS="NOMcom", left_context="geunes et par", right_context="bones oevres firent", label_uniform="tort1", morph="None"),
    WordToken(corpus=Wauchier.id, form="bones", lemma="bon", POS="ADJqua", left_context="et par toutes", right_context="oevres firent tant", label_uniform="bon", morph="None"),
    WordToken(corpus=Wauchier.id, form="oevres", lemma="uevre", POS="NOMcom", left_context="par toutes bones", right_context="firent tant q", label_uniform="uevre", morph="None"),
    WordToken(corpus=Wauchier.id, form="firent", lemma="faire", POS="VERcjg", left_context="toutes bones oevres", right_context="tant q il", label_uniform="faire", morph="None"),
    WordToken(corpus=Wauchier.id, form="tant", lemma="tant", POS="ADVgen", left_context="bones oevres firent", right_context="q il vindrent", label_uniform="tant", morph="None"),
    WordToken(corpus=Wauchier.id, form="q", lemma="que4", POS="CONsub", left_context="oevres firent tant", right_context="il vindrent a", label_uniform="que4", morph="None"),
    WordToken(corpus=Wauchier.id, form="il", lemma="il", POS="PROper", left_context="firent tant q", right_context="vindrent a vie", label_uniform="il", morph="None"),
    WordToken(corpus=Wauchier.id, form="vindrent", lemma="venir", POS="VERcjg", left_context="tant q il", right_context="a vie parmenable", label_uniform="venir", morph="None"),
    WordToken(corpus=Wauchier.id, form="a", lemma="a", POS="PRE", left_context="q il vindrent", right_context="vie parmenable et", label_uniform="a", morph="None"),
    WordToken(corpus=Wauchier.id, form="vie", lemma="vie", POS="NOMcom", left_context="il vindrent a", right_context="parmenable et a", label_uniform="vie", morph="None"),
    WordToken(corpus=Wauchier.id, form="parmenable", lemma="parmenidés", POS="NOMpro", left_context="vindrent a vie", right_context="et a la", label_uniform="parmenides", morph="None"),
    WordToken(corpus=Wauchier.id, form="et", lemma="et", POS="CONcoo", left_context="a vie parmenable", right_context="a la corone", label_uniform="et", morph="None"),
    WordToken(corpus=Wauchier.id, form="a", lemma="a", POS="PRE", left_context="vie parmenable et", right_context="la corone de", label_uniform="a", morph="None"),
    WordToken(corpus=Wauchier.id, form="la", lemma="le", POS="DETdef", left_context="parmenable et a", right_context="corone de gloire", label_uniform="le", morph="None"),
    WordToken(corpus=Wauchier.id, form="corone", lemma="corone", POS="NOMcom", left_context="et a la", right_context="de gloire .", label_uniform="corone", morph="None"),
    WordToken(corpus=Wauchier.id, form="de", lemma="de", POS="PRE", left_context="a la corone", right_context="gloire . A", label_uniform="de", morph="None"),
    WordToken(corpus=Wauchier.id, form="gloire", lemma="gloire", POS="NOMcom", left_context="la corone de", right_context=". A ce", label_uniform="gloire", morph="None"),
    WordToken(corpus=Wauchier.id, form=".", lemma=".", POS="PONfrt", left_context="corone de gloire", right_context="A ce regarderent", label_uniform=".", morph="None"),
    WordToken(corpus=Wauchier.id, form="A", lemma="a", POS="PRE", left_context="de gloire .", right_context="ce regarderent li", label_uniform="a", morph="None"),
    WordToken(corpus=Wauchier.id, form="ce", lemma="ce1", POS="PROdem", left_context="gloire . A", right_context="regarderent li seint", label_uniform="ce1", morph="None"),
    WordToken(corpus=Wauchier.id, form="regarderent", lemma="regarder", POS="VERcjg", left_context=". A ce", right_context="li seint confessors", label_uniform="regarder", morph="None"),
    WordToken(corpus=Wauchier.id, form="li", lemma="le", POS="PROper", left_context="A ce regarderent", right_context="seint confessors et", label_uniform="le", morph="None"),
    WordToken(corpus=Wauchier.id, form="seint", lemma="saint", POS="VERcjg", left_context="ce regarderent li", right_context="confessors et mes", label_uniform="saint", morph="None"),
    WordToken(corpus=Wauchier.id, form="confessors", lemma="confesser", POS="NOMcom", left_context="regarderent li seint", right_context="et mes sires", label_uniform="confesser", morph="None"),
    WordToken(corpus=Wauchier.id, form="et", lemma="et", POS="CONcoo", left_context="li seint confessors", right_context="mes sires seinz", label_uniform="et", morph="None"),
    WordToken(corpus=Wauchier.id, form="mes", lemma="mon1", POS="DETpos", left_context="seint confessors et", right_context="sires seinz Martins", label_uniform="mon1", morph="None"),
    WordToken(corpus=Wauchier.id, form="sires", lemma="seignor", POS="NOMcom", left_context="confessors et mes", right_context="seinz Martins dont", label_uniform="seignor", morph="None"),
    WordToken(corpus=Wauchier.id, form="seinz", lemma="saint", POS="VERcjg", left_context="et mes sires", right_context="Martins dont ci", label_uniform="saint", morph="None"),
    WordToken(corpus=Wauchier.id, form="Martins", lemma="martin", POS="NOMpro", left_context="mes sires seinz", right_context="dont ci comence", label_uniform="martin", morph="None"),
    WordToken(corpus=Wauchier.id, form="dont", lemma="dont", POS="PROrel", left_context="sires seinz Martins", right_context="ci comence la", label_uniform="dont", morph="None"),
    WordToken(corpus=Wauchier.id, form="ci", lemma="ci", POS="ADVgen", left_context="seinz Martins dont", right_context="comence la vie", label_uniform="ci", morph="None"),
    WordToken(corpus=Wauchier.id, form="comence", lemma="comencier", POS="VERcjg", left_context="Martins dont ci", right_context="la vie .", label_uniform="comencier", morph="None"),
    WordToken(corpus=Wauchier.id, form="la", lemma="le", POS="DETdef", left_context="dont ci comence", right_context="vie . Seinz", label_uniform="le", morph="None"),
    WordToken(corpus=Wauchier.id, form="vie", lemma="vie", POS="NOMcom", left_context="ci comence la", right_context=". Seinz Martins", label_uniform="vie", morph="None"),
    WordToken(corpus=Wauchier.id, form=".", lemma=".", POS="PONfrt", left_context="comence la vie", right_context="Seinz Martins fu", label_uniform=".", morph="None"),
    WordToken(corpus=Wauchier.id, form="Seinz", lemma="saint", POS="VERppa", left_context="la vie .", right_context="Martins fu nez", label_uniform="saint", morph="None"),
    WordToken(corpus=Wauchier.id, form="Martins", lemma="martin", POS="NOMpro", left_context="vie . Seinz", right_context="fu nez de", label_uniform="martin", morph="None"),
    WordToken(corpus=Wauchier.id, form="fu", lemma="estre1", POS="VERcjg", left_context=". Seinz Martins", right_context="nez de la", label_uniform="estre1", morph="None"),
    WordToken(corpus=Wauchier.id, form="nez", lemma="naistre", POS="VERppe", left_context="Seinz Martins fu", right_context="de la contree", label_uniform="naistre", morph="None"),
    WordToken(corpus=Wauchier.id, form="de", lemma="de", POS="PRE", left_context="Martins fu nez", right_context="", label_uniform="de", morph="None"),
    WordToken(corpus=Wauchier.id, form="la", lemma="le", POS="DETdef", left_context="fu nez de", right_context="contree de Pannone", label_uniform="le", morph="None"),
    WordToken(corpus=Wauchier.id, form="contree", lemma="contree", POS="NOMcom", left_context="nez de la", right_context="de Pannone ,", label_uniform="contree", morph="None"),
    WordToken(corpus=Wauchier.id, form="de", lemma="de", POS="PRE", left_context="", right_context="Pannone , d", label_uniform="de", morph="None"),
    WordToken(corpus=Wauchier.id, form="Pannone", lemma="prendre", POS="NOMcom", left_context="la contree de", right_context=", d un", label_uniform="prendre", morph="None"),
    WordToken(corpus=Wauchier.id, form=",", lemma=",", POS="PONfbl", left_context="contree de Pannone", right_context="d un chastiel", label_uniform=",", morph="None"),
    WordToken(corpus=Wauchier.id, form="d", lemma="de", POS="PRE", left_context="de Pannone ,", right_context="un chastiel qi", label_uniform="de", morph="None"),
    WordToken(corpus=Wauchier.id, form="un", lemma="un", POS="DETndf", left_context="Pannone , d", right_context="chastiel qi Ysabbarie", label_uniform="un", morph="None"),
    WordToken(corpus=Wauchier.id, form="chastiel", lemma="chastiier", POS="NOMcom", left_context=", d un", right_context="qi Ysabbarie avoit", label_uniform="chastiier", morph="None"),
    WordToken(corpus=Wauchier.id, form="qi", lemma="ci", POS="DETndf", left_context="d un chastiel", right_context="Ysabbarie avoit non", label_uniform="ci", morph="None"),
    WordToken(corpus=Wauchier.id, form="Ysabbarie", lemma="chamberiere", POS="ADJqua", left_context="un chastiel qi", right_context="avoit non .", label_uniform="chamberiere", morph="None"),
    WordToken(corpus=Wauchier.id, form="avoit", lemma="avoir", POS="VERcjg", left_context="chastiel qi Ysabbarie", right_context="non . Si", label_uniform="avoir", morph="None"),
    WordToken(corpus=Wauchier.id, form="non", lemma="nom", POS="NOMcom", left_context="qi Ysabbarie avoit", right_context=". Si fu", label_uniform="nom", morph="None"),
    WordToken(corpus=Wauchier.id, form=".", lemma=".", POS="PONfrt", left_context="Ysabbarie avoit non", right_context="Si fu de", label_uniform=".", morph="None"),
    WordToken(corpus=Wauchier.id, form="Si", lemma="si", POS="ADVgen", left_context="avoit non .", right_context="fu de haute", label_uniform="si", morph="None"),
    WordToken(corpus=Wauchier.id, form="fu", lemma="estre1", POS="VERcjg", left_context="non . Si", right_context="de haute lignie", label_uniform="estre1", morph="None"),
    WordToken(corpus=Wauchier.id, form="de", lemma="de", POS="PRE", left_context=". Si fu", right_context="haute lignie et", label_uniform="de", morph="None"),
    WordToken(corpus=Wauchier.id, form="haute", lemma="haut", POS="ADJqua", left_context="Si fu de", right_context="lignie et de", label_uniform="haut", morph="None"),
    WordToken(corpus=Wauchier.id, form="lignie", lemma="lignage", POS="NOMcom", left_context="fu de haute", right_context="et de par", label_uniform="lignage", morph="None"),
    WordToken(corpus=Wauchier.id, form="et", lemma="et", POS="CONcoo", left_context="de haute lignie", right_context="de par mere", label_uniform="et", morph="None"),
    WordToken(corpus=Wauchier.id, form="de", lemma="de", POS="PRE", left_context="haute lignie et", right_context="par mere et", label_uniform="de", morph="None"),
    WordToken(corpus=Wauchier.id, form="par", lemma="par", POS="PRE", left_context="lignie et de", right_context="mere et de", label_uniform="par", morph="None"),
    WordToken(corpus=Wauchier.id, form="mere", lemma="mere", POS="NOMcom", left_context="et de par", right_context="et de par", label_uniform="mere", morph="None"),
    WordToken(corpus=Wauchier.id, form="et", lemma="et", POS="CONcoo", left_context="de par mere", right_context="de par pere", label_uniform="et", morph="None"),
    WordToken(corpus=Wauchier.id, form="de", lemma="de", POS="PRE", left_context="par mere et", right_context="par pere .", label_uniform="de", morph="None"),
    WordToken(corpus=Wauchier.id, form="par", lemma="par", POS="PRE", left_context="mere et de", right_context="pere . Ses", label_uniform="par", morph="None"),
    WordToken(corpus=Wauchier.id, form="pere", lemma="pere", POS="NOMcom", left_context="et de par", right_context=". Ses peres", label_uniform="pere", morph="None"),
    WordToken(corpus=Wauchier.id, form=".", lemma=".", POS="PONfrt", left_context="de par pere", right_context="Ses peres fu", label_uniform=".", morph="None"),
    WordToken(corpus=Wauchier.id, form="Ses", lemma="son4", POS="DETpos", left_context="par pere .", right_context="peres fu chevaliers", label_uniform="son4", morph="None"),
    WordToken(corpus=Wauchier.id, form="peres", lemma="pere", POS="NOMcom", left_context="pere . Ses", right_context="fu chevaliers et", label_uniform="pere", morph="None"),
    WordToken(corpus=Wauchier.id, form="fu", lemma="estre1", POS="VERcjg", left_context=". Ses peres", right_context="chevaliers et hauz", label_uniform="estre1", morph="None"),
    WordToken(corpus=Wauchier.id, form="chevaliers", lemma="chevalier", POS="NOMcom", left_context="Ses peres fu", right_context="et hauz hom", label_uniform="chevalier", morph="None"),
    WordToken(corpus=Wauchier.id, form="et", lemma="et", POS="CONcoo", left_context="peres fu chevaliers", right_context="", label_uniform="et", morph="None"),
    WordToken(corpus=Wauchier.id, form="hauz", lemma="haut", POS="ADJqua", left_context="fu chevaliers et", right_context="hom et riches", label_uniform="haut", morph="None"),
    WordToken(corpus=Wauchier.id, form="hom", lemma="ome", POS="NOMcom", left_context="chevaliers et hauz", right_context="et riches .", label_uniform="ome", morph="None"),
    WordToken(corpus=Wauchier.id, form="et", lemma="et", POS="CONcoo", left_context="", right_context="riches . Et", label_uniform="et", morph="None"),
    WordToken(corpus=Wauchier.id, form="riches", lemma="riche", POS="ADJqua", left_context="hauz hom et", right_context=". Et il", label_uniform="riche", morph="None"),
    WordToken(corpus=Wauchier.id, form=".", lemma=".", POS="PONfrt", left_context="hom et riches", right_context="Et il comença", label_uniform=".", morph="None"),
    WordToken(corpus=Wauchier.id, form="Et", lemma="et", POS="CONcoo", left_context="et riches .", right_context="il comença tres", label_uniform="et", morph="None"),
    WordToken(corpus=Wauchier.id, form="il", lemma="il", POS="PROper", left_context="riches . Et", right_context="comença tres s", label_uniform="il", morph="None"),
    WordToken(corpus=Wauchier.id, form="comença", lemma="comencier", POS="VERcjg", left_context=". Et il", right_context="tres s enfance", label_uniform="comencier", morph="None"),
    WordToken(corpus=Wauchier.id, form="tres", lemma="très", POS="ADVgen", left_context="Et il comença", right_context="s enfance bones", label_uniform="tres", morph="None"),
    WordToken(corpus=Wauchier.id, form="s", lemma="soi1", POS="ADVgen", left_context="il comença tres", right_context="enfance bones oevres", label_uniform="soi1", morph="None"),
    WordToken(corpus=Wauchier.id, form="enfance", lemma="enfance", POS="NOMcom", left_context="comença tres s", right_context="bones oevres a", label_uniform="enfance", morph="None"),
    WordToken(corpus=Wauchier.id, form="bones", lemma="bon", POS="ADJqua", left_context="tres s enfance", right_context="oevres a feire", label_uniform="bon", morph="None"),
    WordToken(corpus=Wauchier.id, form="oevres", lemma="uevre", POS="NOMcom", left_context="s enfance bones", right_context="a feire et", label_uniform="uevre", morph="None"),
    WordToken(corpus=Wauchier.id, form="a", lemma="a", POS="PRE", left_context="enfance bones oevres", right_context="", label_uniform="a", morph="None"),
    WordToken(corpus=Wauchier.id, form="feire", lemma="faire", POS="VERinf", left_context="bones oevres a", right_context="et a ensivre", label_uniform="faire", morph="None"),
    WordToken(corpus=Wauchier.id, form="et", lemma="et", POS="CONcoo", left_context="oevres a feire", right_context="a ensivre ,", label_uniform="et", morph="None"),
    WordToken(corpus=Wauchier.id, form="a", lemma="a", POS="PRE", left_context="", right_context="ensivre , car", label_uniform="a", morph="None"),
    WordToken(corpus=Wauchier.id, form="ensivre", lemma="ainsi", POS="NOMcom", left_context="feire et a", right_context=", car tres", label_uniform="ainsi", morph="None"),
    WordToken(corpus=Wauchier.id, form=",", lemma=",", POS="PONfbl", left_context="et a ensivre", right_context="car tres ce", label_uniform=",", morph="None"),
    WordToken(corpus=Wauchier.id, form="car", lemma="car", POS="CONcoo", left_context="a ensivre ,", right_context="tres ce q", label_uniform="car", morph="None"),
    WordToken(corpus=Wauchier.id, form="tres", lemma="très", POS="ADVgen", left_context="ensivre , car", right_context="ce q il", label_uniform="tres", morph="None"),
    WordToken(corpus=Wauchier.id, form="ce", lemma="ce2", POS="PROdem", left_context=", car tres", right_context="q il n", label_uniform="ce2", morph="None"),
    WordToken(corpus=Wauchier.id, form="q", lemma=":", POS="PONfrt", left_context="car tres ce", right_context="il n avoit", label_uniform=":", morph="None"),
    WordToken(corpus=Wauchier.id, form="il", lemma="il", POS="PROper", left_context="tres ce q", right_context="n avoit qe", label_uniform="il", morph="None"),
    WordToken(corpus=Wauchier.id, form="n", lemma="ne1", POS="ADVneg", left_context="ce q il", right_context="avoit qe .", label_uniform="ne1", morph="None"),
    WordToken(corpus=Wauchier.id, form="avoit", lemma="avoir", POS="VERcjg", left_context="q il n", right_context="qe . x", label_uniform="avoir", morph="None"),
    WordToken(corpus=Wauchier.id, form="qe", lemma="ce1", POS="PROdem", left_context="il n avoit", right_context=". x .", label_uniform="ce1", morph="None"),
    WordToken(corpus=Wauchier.id, form=".", lemma=".", POS="PONfrt", left_context="n avoit qe", right_context="x . anz", label_uniform=".", morph="None"),
    WordToken(corpus=Wauchier.id, form="x", lemma="»", POS="PONpdr", left_context="avoit qe .", right_context=". anz ,", label_uniform=">>", morph="None"),
    WordToken(corpus=Wauchier.id, form=".", lemma=".", POS="PONfrt", left_context="qe . x", right_context="anz , comença", label_uniform=".", morph="None"),
    WordToken(corpus=Wauchier.id, form="anz", lemma="an", POS="ADVgen", left_context=". x .", right_context=", comença il", label_uniform="an", morph="None"),
    WordToken(corpus=Wauchier.id, form=",", lemma=",", POS="PONfbl", left_context="x . anz", right_context="comença il a", label_uniform=",", morph="None"),
    WordToken(corpus=Wauchier.id, form="comença", lemma="comencier", POS="VERcjg", left_context=". anz ,", right_context="il a aler", label_uniform="comencier", morph="None"),
    WordToken(corpus=Wauchier.id, form="il", lemma="il", POS="PROper", left_context="anz , comença", right_context="a aler a", label_uniform="il", morph="None"),
    WordToken(corpus=Wauchier.id, form="a", lemma="a", POS="PRE", left_context=", comença il", right_context="aler a seinte", label_uniform="a", morph="None"),
    WordToken(corpus=Wauchier.id, form="aler", lemma="aler", POS="VERinf", left_context="comença il a", right_context="a seinte glisse", label_uniform="aler", morph="None"),
    WordToken(corpus=Wauchier.id, form="a", lemma="a", POS="PRE", left_context="il a aler", right_context="seinte glisse maugré", label_uniform="a", morph="None"),
    WordToken(corpus=Wauchier.id, form="seinte", lemma="saint", POS="ADJqua", left_context="a aler a", right_context="glisse maugré son", label_uniform="saint", morph="None"),
]


WauchierAllowedLemma = [
    AllowedLemma(label="de", label_uniform="de", control_list=WCL.id),
    AllowedLemma(label="saint", label_uniform="saint", control_list=WCL.id),
    AllowedLemma(label="martin", label_uniform="martin", control_list=WCL.id),
    AllowedLemma(label="öir", label_uniform="öir", control_list=WCL.id),
    AllowedLemma(label="car", label_uniform="car", control_list=WCL.id),
    AllowedLemma(label="devoir", label_uniform="devoir", control_list=WCL.id),
    AllowedLemma(label="entendre", label_uniform="entendre", control_list=WCL.id),
    AllowedLemma(label=",", label_uniform=",", control_list=WCL.id),
    AllowedLemma(label="par", label_uniform="par", control_list=WCL.id),
    AllowedLemma(label="un", label_uniform="un", control_list=WCL.id),
    AllowedLemma(label="pöoir", label_uniform="pöoir", control_list=WCL.id),
    AllowedLemma(label="il", label_uniform="il", control_list=WCL.id),
    AllowedLemma(label="doucement", label_uniform="doucement", control_list=WCL.id),
    AllowedLemma(label="en1", label_uniform="en1", control_list=WCL.id),
    AllowedLemma(label="le", label_uniform="le", control_list=WCL.id),
    AllowedLemma(label="mout", label_uniform="mout", control_list=WCL.id),
    AllowedLemma(label="bien", label_uniform="bien", control_list=WCL.id),
    AllowedLemma(label="retenir", label_uniform="retenir", control_list=WCL.id),
    AllowedLemma(label="volentiers", label_uniform="volentiers", control_list=WCL.id),
    AllowedLemma(label="et", label_uniform="et", control_list=WCL.id),
    AllowedLemma(label="savoir", label_uniform="savoir", control_list=WCL.id)
]

WauchierAllowedPOS = [
    AllowedPOS(label='ADJqua', control_list=WCL.id),
    AllowedPOS(label='NOMpro', control_list=WCL.id),
    AllowedPOS(label='CONcoo', control_list=WCL.id),
    AllowedPOS(label='DETdef', control_list=WCL.id),
    AllowedPOS(label='PROper', control_list=WCL.id),
    AllowedPOS(label='ADVgen', control_list=WCL.id),
    AllowedPOS(label='PONfbl', control_list=WCL.id),
    AllowedPOS(label='VERcjg', control_list=WCL.id),
    AllowedPOS(label='PRE', control_list=WCL.id),
    AllowedPOS(label='VERinf', control_list=WCL.id)
]

WauchierAllowedMorph = [
    AllowedMorph(control_list=WCL.id, label="_", readable="pas de morphologie"),
    AllowedMorph(control_list=WCL.id, label="DEGRE=-", readable="non applicable"),
    AllowedMorph(control_list=WCL.id, label="MODE=imp|PERS.=2|NOMB.=p", readable="impératif 2e personne pluriel"),
    AllowedMorph(control_list=WCL.id, label="MODE=ind|TEMPS=psp|PERS.=3|NOMB.=s", readable="indicatif passé simple 3e personne singulier"),
    AllowedMorph(control_list=WCL.id, label="MODE=ind|TEMPS=pst|PERS.=1|NOMB.=s", readable="indicatif présent 1re personne singulier"),
    AllowedMorph(control_list=WCL.id, label="MODE=sub|TEMPS=pst|PERS.=3|NOMB.=s", readable="subjonctif présent 3e personne singulier"),
    AllowedMorph(control_list=WCL.id, label="NOMB.=p|GENRE=m|CAS=n", readable="pluriel masculin nominatif"),
    AllowedMorph(control_list=WCL.id, label="NOMB.=p|GENRE=m|CAS=r", readable="pluriel masculin régime"),
    AllowedMorph(control_list=WCL.id, label="NOMB.=s|GENRE=f|CAS=r", readable="singulier féminin régime"),
    AllowedMorph(control_list=WCL.id, label="NOMB.=s|GENRE=f|CAS=r|DEGRE=p", readable="singulier féminin régime positif"),
    AllowedMorph(control_list=WCL.id, label="NOMB.=s|GENRE=m|CAS=n", readable="singulier masculin nominatif"),
    AllowedMorph(control_list=WCL.id, label="NOMB.=s|GENRE=m|CAS=r", readable="singulier masculin régime"),
    AllowedMorph(control_list=WCL.id, label="PERS.=1|NOMB.=s|GENRE=m|CAS=n", readable="1re personne singulier masculin nominatif"),
    AllowedMorph(control_list=WCL.id, label="PERS.=2|NOMB.=p|GENRE=m|CAS=r", readable="2e personne pluriel masculin régime"),
    AllowedMorph(control_list=WCL.id, label="PERS.=3|NOMB.=p|GENRE=m|CAS=r", readable="3e personne pluriel masculin régime")
]
