from app.models import Corpus, WordToken, AllowedLemma, AllowedPOS

Wauchier = Corpus(name="Wauchier", id=1)

WauchierTokens = [
    WordToken(corpus=1, form="De", lemma="de", POS="PRE", context="De seint Martin mout", label_uniform="de", morph="None"),
    WordToken(corpus=1, form="seint", lemma="saint", POS="ADJqua", context="De seint Martin mout doit", label_uniform="saint", morph="None"),
    WordToken(corpus=1, form="Martin", lemma="martin", POS="NOMpro", context="De seint Martin mout doit on", label_uniform="martin", morph="None"),
    WordToken(corpus=1, form="mout", lemma="mout", POS="ADVgen", context="De seint Martin mout doit on doucement", label_uniform="mout", morph="None"),
    WordToken(corpus=1, form="doit", lemma="devoir", POS="VERcjg", context="seint Martin mout doit on doucement et", label_uniform="devoir", morph="None"),
    WordToken(corpus=1, form="on", lemma="un", POS="PRE", context="Martin mout doit on doucement et volentiers", label_uniform="un", morph="None"),
    WordToken(corpus=1, form="doucement", lemma="doucement", POS="ADVgen", context="mout doit on doucement et volentiers le", label_uniform="doucement", morph="None"),
    WordToken(corpus=1, form="et", lemma="et", POS="CONcoo", context="doit on doucement et volentiers le bien", label_uniform="et", morph="None"),
    WordToken(corpus=1, form="volentiers", lemma="volentiers", POS="ADVgen", context="on doucement et volentiers le bien oïr", label_uniform="volentiers", morph="None"),
    WordToken(corpus=1, form="le", lemma="le", POS="DETdef", context="doucement et volentiers le bien oïr et", label_uniform="le", morph="None"),
    WordToken(corpus=1, form="bien", lemma="bien", POS="ADVgen", context="et volentiers le bien oïr et entendre", label_uniform="bien", morph="None"),
    WordToken(corpus=1, form="oïr", lemma="öir", POS="VERinf", context="volentiers le bien oïr et entendre ,", label_uniform="oir", morph="None"),
    WordToken(corpus=1, form="et", lemma="et", POS="CONcoo", context="le bien oïr et entendre , car", label_uniform="et", morph="None"),
    WordToken(corpus=1, form="entendre", lemma="entendre", POS="VERinf", context="bien oïr et entendre , car par", label_uniform="entendre", morph="None"),
    WordToken(corpus=1, form=",", lemma=",", POS="PONfbl", context="oïr et entendre , car par le", label_uniform=",", morph="None"),
    WordToken(corpus=1, form="car", lemma="car", POS="CONcoo", context="et entendre , car par le bien", label_uniform="car", morph="None"),
    WordToken(corpus=1, form="par", lemma="par", POS="PRE", context="entendre , car par le bien savoir", label_uniform="par", morph="None"),
    WordToken(corpus=1, form="le", lemma="le", POS="DETdef", context=", car par le bien savoir et", label_uniform="le", morph="None"),
    WordToken(corpus=1, form="bien", lemma="bien", POS="ADVgen", context="car par le bien savoir et retenir", label_uniform="bien", morph="None"),
    WordToken(corpus=1, form="savoir", lemma="savoir", POS="VERinf", context="par le bien savoir et retenir puet", label_uniform="savoir", morph="None"),
    WordToken(corpus=1, form="et", lemma="et", POS="CONcoo", context="le bien savoir et retenir puet l", label_uniform="et", morph="None"),
    WordToken(corpus=1, form="retenir", lemma="retenir", POS="VERinf", context="bien savoir et retenir puet l en", label_uniform="retenir", morph="None"),
    WordToken(corpus=1, form="puet", lemma="pöoir", POS="VERcjg", context="savoir et retenir puet l en sovent", label_uniform="pooir", morph="None"),
    WordToken(corpus=1, form="l", lemma="il", POS="PROper", context="et retenir puet l en sovent a", label_uniform="il", morph="None"),
    WordToken(corpus=1, form="en", lemma="en1", POS="PRE", context="retenir puet l en sovent a bien", label_uniform="en1", morph="None"),
    WordToken(corpus=1, form="sovent", lemma="savoir", POS="VERcjg", context="puet l en sovent a bien venir", label_uniform="savoir", morph="None"),
    WordToken(corpus=1, form="a", lemma="a", POS="PRE", context="l en sovent a bien venir .", label_uniform="a", morph="None"),
    WordToken(corpus=1, form="bien", lemma="bien", POS="ADVgen", context="en sovent a bien venir . Qui", label_uniform="bien", morph="None"),
    WordToken(corpus=1, form="venir", lemma="venir", POS="VERinf", context="sovent a bien venir . Qui bien", label_uniform="venir", morph="None"),
    WordToken(corpus=1, form=".", lemma=".", POS="PONfrt", context="a bien venir . Qui bien ne", label_uniform=".", morph="None"),
    WordToken(corpus=1, form="Qui", lemma="que2/3", POS="PROrel", context="bien venir . Qui bien ne seit", label_uniform="que2/3", morph="None"),
    WordToken(corpus=1, form="bien", lemma="bien", POS="ADVgen", context="venir . Qui bien ne seit ne", label_uniform="bien", morph="None"),
    WordToken(corpus=1, form="ne", lemma="ne1", POS="ADVneg", context=". Qui bien ne seit ne bien", label_uniform="ne1", morph="None"),
    WordToken(corpus=1, form="seit", lemma="estre1", POS="VERcjg", context="Qui bien ne seit ne bien n", label_uniform="estre1", morph="None"),
    WordToken(corpus=1, form="ne", lemma="ne2", POS="CONcoo", context="bien ne seit ne bien n entent", label_uniform="ne2", morph="None"),
    WordToken(corpus=1, form="bien", lemma="bien", POS="ADVgen", context="ne seit ne bien n entent de", label_uniform="bien", morph="None"),
    WordToken(corpus=1, form="n", lemma="ne1", POS="ADVneg", context="seit ne bien n entent de bien", label_uniform="ne1", morph="None"),
    WordToken(corpus=1, form="entent", lemma="entendre", POS="VERcjg", context="ne bien n entent de bien faire", label_uniform="entendre", morph="None"),
    WordToken(corpus=1, form="de", lemma="de", POS="PRE", context="bien n entent de bien faire n", label_uniform="de", morph="None"),
    WordToken(corpus=1, form="bien", lemma="bien", POS="ADVgen", context="n entent de bien faire n a", label_uniform="bien", morph="None"),
    WordToken(corpus=1, form="faire", lemma="faire", POS="VERinf", context="entent de bien faire n a nul", label_uniform="faire", morph="None"),
    WordToken(corpus=1, form="n", lemma="ne1", POS="ADVneg", context="de bien faire n a nul talent", label_uniform="ne1", morph="None"),
    WordToken(corpus=1, form="a", lemma="a", POS="PRE", context="bien faire n a nul talent .", label_uniform="a", morph="None"),
    WordToken(corpus=1, form="nul", lemma="nul", POS="DETind", context="faire n a nul talent . Mes", label_uniform="nul", morph="None"),
    WordToken(corpus=1, form="talent", lemma="talent", POS="NOMcom", context="n a nul talent . Mes del", label_uniform="talent", morph="None"),
    WordToken(corpus=1, form=".", lemma=".", POS="PONfrt", context="a nul talent . Mes del bien", label_uniform=".", morph="None"),
    WordToken(corpus=1, form="Mes", lemma="mais1", POS="CONcoo", context="nul talent . Mes del bien nest", label_uniform="mais1", morph="None"),
    WordToken(corpus=1, form="del", lemma="de", POS="PRE.DETdef", context="talent . Mes del bien nest sovent", label_uniform="de", morph="None"),
    WordToken(corpus=1, form="bien", lemma="bien", POS="ADVgen", context=". Mes del bien nest sovent li", label_uniform="bien", morph="None"),
    WordToken(corpus=1, form="nest", lemma="naistre", POS="VERcjg", context="Mes del bien nest sovent li biens", label_uniform="naistre", morph="None"),
    WordToken(corpus=1, form="sovent", lemma="savoir", POS="VERcjg", context="del bien nest sovent li biens ,", label_uniform="savoir", morph="None"),
    WordToken(corpus=1, form="li", lemma="le", POS="DETdef", context="bien nest sovent li biens , del", label_uniform="le", morph="None"),
    WordToken(corpus=1, form="biens", lemma="bien", POS="NOMcom", context="nest sovent li biens , del mal", label_uniform="bien", morph="None"),
    WordToken(corpus=1, form=",", lemma=",", POS="PONfbl", context="sovent li biens , del mal li", label_uniform=",", morph="None"),
    WordToken(corpus=1, form="del", lemma="de", POS="PRE.DETdef", context="li biens , del mal li maus", label_uniform="de", morph="None"),
    WordToken(corpus=1, form="mal", lemma="mal1", POS="NOMcom", context="biens , del mal li maus si", label_uniform="mal1", morph="None"),
    WordToken(corpus=1, form="li", lemma="il", POS="PROper", context=", del mal li maus si com", label_uniform="il", morph="None"),
    WordToken(corpus=1, form="maus", lemma="mal1", POS="NOMcom", context="del mal li maus si com dist", label_uniform="mal1", morph="None"),
    WordToken(corpus=1, form="si", lemma="si", POS="ADVgen", context="mal li maus si com dist l", label_uniform="si", morph="None"),
    WordToken(corpus=1, form="com", lemma="come1", POS="CONsub", context="li maus si com dist l Escriture", label_uniform="come1", morph="None"),
    WordToken(corpus=1, form="dist", lemma="dire", POS="VERcjg", context="maus si com dist l Escriture .", label_uniform="dire", morph="None"),
    WordToken(corpus=1, form="l", lemma="le", POS="DETdef", context="si com dist l Escriture . Por", label_uniform="le", morph="None"),
    WordToken(corpus=1, form="Escriture", lemma="escrire", POS="NOMcom", context="com dist l Escriture . Por ce", label_uniform="escrire", morph="None"),
    WordToken(corpus=1, form=".", lemma=".", POS="PONfrt", context="dist l Escriture . Por ce se", label_uniform=".", morph="None"),
    WordToken(corpus=1, form="Por", lemma="por2", POS="PRE", context="l Escriture . Por ce se doit", label_uniform="por2", morph="None"),
    WordToken(corpus=1, form="ce", lemma="ce1", POS="PROdem", context="Escriture . Por ce se doit l", label_uniform="ce1", morph="None"),
    WordToken(corpus=1, form="se", lemma="soi1", POS="PROper", context=". Por ce se doit l en", label_uniform="soi1", morph="None"),
    WordToken(corpus=1, form="doit", lemma="devoir", POS="VERcjg", context="Por ce se doit l en au", label_uniform="devoir", morph="None"),
    WordToken(corpus=1, form="l", lemma="il", POS="PROper", context="ce se doit l en au bien", label_uniform="il", morph="None"),
    WordToken(corpus=1, form="en", lemma="en1", POS="PRE", context="se doit l en au bien avoier", label_uniform="en1", morph="None"),
    WordToken(corpus=1, form="au", lemma="a", POS="PRE.DETdef", context="doit l en au bien avoier et", label_uniform="a", morph="None"),
    WordToken(corpus=1, form="bien", lemma="bien", POS="ADVgen", context="l en au bien avoier et le", label_uniform="bien", morph="None"),
    WordToken(corpus=1, form="avoier", lemma="avoir", POS="VERinf", context="en au bien avoier et le bien", label_uniform="avoir", morph="None"),
    WordToken(corpus=1, form="et", lemma="et", POS="CONcoo", context="au bien avoier et le bien feire", label_uniform="et", morph="None"),
    WordToken(corpus=1, form="le", lemma="le", POS="DETdef", context="bien avoier et le bien feire ,", label_uniform="le", morph="None"),
    WordToken(corpus=1, form="bien", lemma="bien", POS="ADVgen", context="avoier et le bien feire , si", label_uniform="bien", morph="None"),
    WordToken(corpus=1, form="feire", lemma="faire", POS="VERinf", context="et le bien feire , si com", label_uniform="faire", morph="None"),
    WordToken(corpus=1, form=",", lemma=",", POS="PONfbl", context="le bien feire , si com li", label_uniform=",", morph="None"),
    WordToken(corpus=1, form="si", lemma="si", POS="ADVgen", context="bien feire , si com li seint", label_uniform="si", morph="None"),
    WordToken(corpus=1, form="com", lemma="come1", POS="CONsub", context="feire , si com li seint home", label_uniform="come1", morph="None"),
    WordToken(corpus=1, form="li", lemma="le", POS="PROper", context=", si com li seint home firent", label_uniform="le", morph="None"),
    WordToken(corpus=1, form="seint", lemma="saint", POS="VERcjg", context="si com li seint home firent ça", label_uniform="saint", morph="None"),
    WordToken(corpus=1, form="home", lemma="ome", POS="NOMcom", context="com li seint home firent ça en", label_uniform="ome", morph="None"),
    WordToken(corpus=1, form="firent", lemma="faire", POS="VERcjg", context="li seint home firent ça en arriere", label_uniform="faire", morph="None"),
    WordToken(corpus=1, form="ça", lemma="ça", POS="ADVgen", context="seint home firent ça en arriere de", label_uniform="ca", morph="None"),
    WordToken(corpus=1, form="en", lemma="en1", POS="PRE", context="home firent ça en arriere de cui", label_uniform="en1", morph="None"),
    WordToken(corpus=1, form="arriere", lemma="ariere", POS="ADVgen", context="firent ça en arriere de cui nos", label_uniform="ariere", morph="None"),
    WordToken(corpus=1, form="de", lemma="de", POS="PRE", context="ça en arriere de cui nos trovons", label_uniform="de", morph="None"),
    WordToken(corpus=1, form="cui", lemma="que2/3", POS="PROrel", context="en arriere de cui nos trovons les", label_uniform="que2/3", morph="None"),
    WordToken(corpus=1, form="nos", lemma="nos1", POS="PROper", context="arriere de cui nos trovons les oevres", label_uniform="nos1", morph="None"),
    WordToken(corpus=1, form="trovons", lemma="trover", POS="VERcjg", context="de cui nos trovons les oevres et", label_uniform="trover", morph="None"),
    WordToken(corpus=1, form="les", lemma="le", POS="DETdef", context="cui nos trovons les oevres et les", label_uniform="le", morph="None"),
    WordToken(corpus=1, form="oevres", lemma="uevre", POS="NOMcom", context="nos trovons les oevres et les vies", label_uniform="uevre", morph="None"),
    WordToken(corpus=1, form="et", lemma="et", POS="CONcoo", context="trovons les oevres et les vies escriptures", label_uniform="et", morph="None"),
    WordToken(corpus=1, form="les", lemma="le", POS="DETdef", context="les oevres et les vies escriptures .", label_uniform="le", morph="None"),
    WordToken(corpus=1, form="vies", lemma="vie", POS="NOMcom", context="oevres et les vies escriptures . Et", label_uniform="vie", morph="None"),
    WordToken(corpus=1, form="escriptures", lemma="escrever", POS="VERppe", context="et les vies escriptures . Et bien", label_uniform="escrever", morph="None"),
    WordToken(corpus=1, form=".", lemma=".", POS="PONfrt", context="les vies escriptures . Et bien sacent", label_uniform=".", morph="None"),
    WordToken(corpus=1, form="Et", lemma="et", POS="CONcoo", context="vies escriptures . Et bien sacent tuit", label_uniform="et", morph="None"),
    WordToken(corpus=1, form="bien", lemma="bien", POS="ADVgen", context="escriptures . Et bien sacent tuit cil", label_uniform="bien", morph="None"),
    WordToken(corpus=1, form="sacent", lemma="savoir", POS="VERcjg", context=". Et bien sacent tuit cil qi", label_uniform="savoir", morph="None"),
    WordToken(corpus=1, form="tuit", lemma="tot", POS="DETind", context="Et bien sacent tuit cil qi vivent", label_uniform="tot", morph="None"),
    WordToken(corpus=1, form="cil", lemma="cel", POS="PROdem", context="bien sacent tuit cil qi vivent qe", label_uniform="cel", morph="None"),
    WordToken(corpus=1, form="qi", lemma="ci", POS="PROper", context="sacent tuit cil qi vivent qe ja", label_uniform="ci", morph="None"),
    WordToken(corpus=1, form="vivent", lemma="vëoir", POS="VERcjg", context="tuit cil qi vivent qe ja n", label_uniform="veoir", morph="None"),
    WordToken(corpus=1, form="qe", lemma="ce1", POS="PROdem", context="cil qi vivent qe ja n auront", label_uniform="ce1", morph="None"),
    WordToken(corpus=1, form="ja", lemma="ja", POS="ADVgen", context="qi vivent qe ja n auront tant", label_uniform="ja", morph="None"),
    WordToken(corpus=1, form="n", lemma="ne1", POS="ADVneg", context="vivent qe ja n auront tant de", label_uniform="ne1", morph="None"),
    WordToken(corpus=1, form="auront", lemma="aucun", POS="VERcjg", context="qe ja n auront tant de bien", label_uniform="aucun", morph="None"),
    WordToken(corpus=1, form="tant", lemma="tant", POS="ADVgen", context="ja n auront tant de bien fet", label_uniform="tant", morph="None"),
    WordToken(corpus=1, form="de", lemma="de", POS="PRE", context="n auront tant de bien fet en", label_uniform="de", morph="None"),
    WordToken(corpus=1, form="bien", lemma="bien", POS="ADVgen", context="auront tant de bien fet en totes", label_uniform="bien", morph="None"),
    WordToken(corpus=1, form="fet", lemma="faire", POS="VERppe", context="tant de bien fet en totes lor", label_uniform="faire", morph="None"),
    WordToken(corpus=1, form="en", lemma="en1", POS="PRE", context="de bien fet en totes lor vies", label_uniform="en1", morph="None"),
    WordToken(corpus=1, form="totes", lemma="tot", POS="DETind", context="bien fet en totes lor vies qe", label_uniform="tot", morph="None"),
    WordToken(corpus=1, form="lor", lemma="lor2", POS="DETpos", context="fet en totes lor vies qe qant", label_uniform="lor2", morph="None"),
    WordToken(corpus=1, form="vies", lemma="vie", POS="NOMcom", context="en totes lor vies qe qant la", label_uniform="vie", morph="None"),
    WordToken(corpus=1, form="qe", lemma="ce1", POS="PROdem", context="totes lor vies qe qant la mort", label_uniform="ce1", morph="None"),
    WordToken(corpus=1, form="qant", lemma="cant1", POS="CONsub", context="lor vies qe qant la mort dont", label_uniform="cant1", morph="None"),
    WordToken(corpus=1, form="la", lemma="le", POS="DETdef", context="vies qe qant la mort dont nule", label_uniform="le", morph="None"),
    WordToken(corpus=1, form="mort", lemma="mort", POS="NOMcom", context="qe qant la mort dont nule rien", label_uniform="mort", morph="None"),
    WordToken(corpus=1, form="dont", lemma="dont", POS="PROrel", context="qant la mort dont nule rien n", label_uniform="dont", morph="None"),
    WordToken(corpus=1, form="nule", lemma="nul", POS="DETind", context="la mort dont nule rien n eschape", label_uniform="nul", morph="None"),
    WordToken(corpus=1, form="rien", lemma="rien", POS="NOMcom", context="mort dont nule rien n eschape les", label_uniform="rien", morph="None"),
    WordToken(corpus=1, form="n", lemma="ne1", POS="ADVneg", context="dont nule rien n eschape les poindera", label_uniform="ne1", morph="None"),
    WordToken(corpus=1, form="eschape", lemma="eschaper", POS="VERcjg", context="nule rien n eschape les poindera au", label_uniform="eschaper", morph="None"),
    WordToken(corpus=1, form="les", lemma="le", POS="DETdef", context="rien n eschape les poindera au cuer", label_uniform="le", morph="None"),
    WordToken(corpus=1, form="poindera", lemma="poindre", POS="VERcjg", context="n eschape les poindera au cuer q", label_uniform="poindre", morph="None"),
    WordToken(corpus=1, form="au", lemma="a", POS="PRE.DETdef", context="eschape les poindera au cuer q il", label_uniform="a", morph="None"),
    WordToken(corpus=1, form="cuer", lemma="cuer2", POS="NOMcom", context="les poindera au cuer q il ne", label_uniform="cuer2", morph="None"),
    WordToken(corpus=1, form="q", lemma=":", POS="PONfrt", context="poindera au cuer q il ne cuident", label_uniform=":", morph="None"),
    WordToken(corpus=1, form="il", lemma="il", POS="PROper", context="au cuer q il ne cuident petit", label_uniform="il", morph="None"),
    WordToken(corpus=1, form="ne", lemma="ne1", POS="ADVneg", context="cuer q il ne cuident petit avoir", label_uniform="ne1", morph="None"),
    WordToken(corpus=1, form="cuident", lemma="cuidier", POS="VERcjg", context="q il ne cuident petit avoir fait", label_uniform="cuidier", morph="None"),
    WordToken(corpus=1, form="petit", lemma="petit", POS="ADJqua", context="il ne cuident petit avoir fait .", label_uniform="petit", morph="None"),
    WordToken(corpus=1, form="avoir", lemma="avoir", POS="VERinf", context="ne cuident petit avoir fait . Dex", label_uniform="avoir", morph="None"),
    WordToken(corpus=1, form="fait", lemma="faire", POS="VERppe", context="cuident petit avoir fait . Dex !", label_uniform="faire", morph="None"),
    WordToken(corpus=1, form=".", lemma=".", POS="PONfrt", context="petit avoir fait . Dex ! Qe", label_uniform=".", morph="None"),
    WordToken(corpus=1, form="Dex", lemma="dieu", POS="NOMpro", context="avoir fait . Dex ! Qe feront", label_uniform="dieu", morph="None"),
    WordToken(corpus=1, form="!", lemma="!", POS="PONfrt", context="fait . Dex ! Qe feront dont", label_uniform="!", morph="None"),
    WordToken(corpus=1, form="Qe", lemma="ce1", POS="PROdem", context=". Dex ! Qe feront dont cil", label_uniform="ce1", morph="None"),
    WordToken(corpus=1, form="feront", lemma="faire", POS="VERcjg", context="Dex ! Qe feront dont cil qui", label_uniform="faire", morph="None"),
    WordToken(corpus=1, form="dont", lemma="dont", POS="PROrel", context="! Qe feront dont cil qui riche", label_uniform="dont", morph="None"),
    WordToken(corpus=1, form="cil", lemma="cel", POS="PROdem", context="Qe feront dont cil qui riche sont", label_uniform="cel", morph="None"),
    WordToken(corpus=1, form="qui", lemma="que2/3", POS="PROrel", context="feront dont cil qui riche sont et", label_uniform="que2/3", morph="None"),
    WordToken(corpus=1, form="riche", lemma="riche", POS="ADJqua", context="dont cil qui riche sont et aise", label_uniform="riche", morph="None"),
    WordToken(corpus=1, form="sont", lemma="estre1", POS="VERcjg", context="cil qui riche sont et aise de", label_uniform="estre1", morph="None"),
    WordToken(corpus=1, form="et", lemma="et", POS="CONcoo", context="qui riche sont et aise de l", label_uniform="et", morph="None"),
    WordToken(corpus=1, form="aise", lemma="aise", POS="NOMcom", context="riche sont et aise de l avoir", label_uniform="aise", morph="None"),
    WordToken(corpus=1, form="de", lemma="de", POS="PRE", context="sont et aise de l avoir de", label_uniform="de", morph="None"),
    WordToken(corpus=1, form="l", lemma="le", POS="DETdef", context="et aise de l avoir de cest", label_uniform="le", morph="None"),
    WordToken(corpus=1, form="avoir", lemma="avoir", POS="VERinf", context="aise de l avoir de cest siecle", label_uniform="avoir", morph="None"),
    WordToken(corpus=1, form="de", lemma="de", POS="PRE", context="de l avoir de cest siecle ,", label_uniform="de", morph="None"),
    WordToken(corpus=1, form="cest", lemma="cest", POS="DETdem", context="l avoir de cest siecle , ne", label_uniform="cest", morph="None"),
    WordToken(corpus=1, form="siecle", lemma="siecle", POS="NOMcom", context="avoir de cest siecle , ne en", label_uniform="siecle", morph="None"),
    WordToken(corpus=1, form=",", lemma=",", POS="PONfbl", context="de cest siecle , ne en eus", label_uniform=",", morph="None"),
    WordToken(corpus=1, form="ne", lemma="ne2", POS="CONcoo", context="cest siecle , ne en eus n", label_uniform="ne2", morph="None"),
    WordToken(corpus=1, form="en", lemma="en2", POS="PROadv", context="siecle , ne en eus n ont", label_uniform="en2", morph="None"),
    WordToken(corpus=1, form="eus", lemma="estre1", POS="VERcjg", context=", ne en eus n ont douçor", label_uniform="estre1", morph="None"),
    WordToken(corpus=1, form="n", lemma="ne1", POS="ADVneg", context="ne en eus n ont douçor ne", label_uniform="ne1", morph="None"),
    WordToken(corpus=1, form="ont", lemma="avoir", POS="VERcjg", context="en eus n ont douçor ne humilité", label_uniform="avoir", morph="None"),
    WordToken(corpus=1, form="douçor", lemma="douçor", POS="NOMcom", context="eus n ont douçor ne humilité ne", label_uniform="doucor", morph="None"),
    WordToken(corpus=1, form="ne", lemma="ne2", POS="CONcoo", context="n ont douçor ne humilité ne misericorde", label_uniform="ne2", morph="None"),
    WordToken(corpus=1, form="humilité", lemma="umelité", POS="NOMcom", context="ont douçor ne humilité ne misericorde ,", label_uniform="umelite", morph="None"),
    WordToken(corpus=1, form="ne", lemma="ne2", POS="CONcoo", context="douçor ne humilité ne misericorde , ainz", label_uniform="ne2", morph="None"),
    WordToken(corpus=1, form="misericorde", lemma="misericorde", POS="NOMcom", context="ne humilité ne misericorde , ainz sont", label_uniform="misericorde", morph="None"),
    WordToken(corpus=1, form=",", lemma=",", POS="PONfbl", context="humilité ne misericorde , ainz sont plein", label_uniform=",", morph="None"),
    WordToken(corpus=1, form="ainz", lemma="ainz", POS="ADVgen", context="ne misericorde , ainz sont plein d", label_uniform="ainz", morph="None"),
    WordToken(corpus=1, form="sont", lemma="estre1", POS="VERcjg", context="misericorde , ainz sont plein d angoisse", label_uniform="estre1", morph="None"),
    WordToken(corpus=1, form="plein", lemma="plein", POS="ADJqua", context=", ainz sont plein d angoisse et", label_uniform="plein", morph="None"),
    WordToken(corpus=1, form="d", lemma="de", POS="PRE", context="ainz sont plein d angoisse et de", label_uniform="de", morph="None"),
    WordToken(corpus=1, form="angoisse", lemma="angoisse", POS="NOMcom", context="sont plein d angoisse et de traïsson", label_uniform="angoisse", morph="None"),
    WordToken(corpus=1, form="et", lemma="et", POS="CONcoo", context="plein d angoisse et de traïsson et", label_uniform="et", morph="None"),
    WordToken(corpus=1, form="de", lemma="de", POS="PRE", context="d angoisse et de traïsson et de", label_uniform="de", morph="None"),
    WordToken(corpus=1, form="traïsson", lemma="träir", POS="NOMcom", context="angoisse et de traïsson et de felonie", label_uniform="trair", morph="None"),
    WordToken(corpus=1, form="et", lemma="et", POS="CONcoo", context="et de traïsson et de felonie et", label_uniform="et", morph="None"),
    WordToken(corpus=1, form="de", lemma="de", POS="PRE", context="de traïsson et de felonie et de", label_uniform="de", morph="None"),
    WordToken(corpus=1, form="felonie", lemma="felonie", POS="NOMcom", context="traïsson et de felonie et de si", label_uniform="felonie", morph="None"),
    WordToken(corpus=1, form="et", lemma="et", POS="CONcoo", context="et de felonie et de si grant", label_uniform="et", morph="None"),
    WordToken(corpus=1, form="de", lemma="de", POS="PRE", context="de felonie et de si grant avarice", label_uniform="de", morph="None"),
    WordToken(corpus=1, form="si", lemma="si", POS="ADVgen", context="felonie et de si grant avarice qe", label_uniform="si", morph="None"),
    WordToken(corpus=1, form="grant", lemma="grant", POS="ADJqua", context="et de si grant avarice qe com", label_uniform="grant", morph="None"),
    WordToken(corpus=1, form="avarice", lemma="aparler", POS="NOMcom", context="de si grant avarice qe com plus", label_uniform="aparler", morph="None"),
    WordToken(corpus=1, form="qe", lemma="ce1", POS="PROper", context="si grant avarice qe com plus ont", label_uniform="ce1", morph="None"),
    WordToken(corpus=1, form="com", lemma="come1", POS="CONsub", context="grant avarice qe com plus ont richesces", label_uniform="come1", morph="None"),
    WordToken(corpus=1, form="plus", lemma="plus", POS="ADVgen", context="avarice qe com plus ont richesces et", label_uniform="plus", morph="None"),
    WordToken(corpus=1, form="ont", lemma="avoir", POS="VERcjg", context="qe com plus ont richesces et avoirs", label_uniform="avoir", morph="None"),
    WordToken(corpus=1, form="richesces", lemma="richece", POS="NOMcom", context="com plus ont richesces et avoirs ,", label_uniform="richece", morph="None"),
    WordToken(corpus=1, form="et", lemma="et", POS="CONcoo", context="plus ont richesces et avoirs , plus", label_uniform="et", morph="None"),
    WordToken(corpus=1, form="avoirs", lemma="avoir", POS="VERinf", context="ont richesces et avoirs , plus en", label_uniform="avoir", morph="None"),
    WordToken(corpus=1, form=",", lemma=",", POS="PONfbl", context="richesces et avoirs , plus en desirrent", label_uniform=",", morph="None"),
    WordToken(corpus=1, form="plus", lemma="plus", POS="ADVgen", context="et avoirs , plus en desirrent a", label_uniform="plus", morph="None"),
    WordToken(corpus=1, form="en", lemma="en2", POS="PROadv", context="avoirs , plus en desirrent a avoir", label_uniform="en2", morph="None"),
    WordToken(corpus=1, form="desirrent", lemma="desirrer", POS="VERcjg", context=", plus en desirrent a avoir ?", label_uniform="desirrer", morph="None"),
    WordToken(corpus=1, form="a", lemma="a", POS="PRE", context="plus en desirrent a avoir ? Ce", label_uniform="a", morph="None"),
    WordToken(corpus=1, form="avoir", lemma="avoir", POS="VERinf", context="en desirrent a avoir ? Ce fet", label_uniform="avoir", morph="None"),
    WordToken(corpus=1, form="?", lemma="?", POS="PONfrt", context="desirrent a avoir ? Ce fet li", label_uniform="?", morph="None"),
    WordToken(corpus=1, form="Ce", lemma="ce1", POS="PROdem", context="a avoir ? Ce fet li deables", label_uniform="ce1", morph="None"),
    WordToken(corpus=1, form="fet", lemma="faire", POS="VERcjg", context="avoir ? Ce fet li deables qi", label_uniform="faire", morph="None"),
    WordToken(corpus=1, form="li", lemma="le", POS="DETdef", context="? Ce fet li deables qi en", label_uniform="le", morph="None"),
    WordToken(corpus=1, form="deables", lemma="dïable", POS="NOMcom", context="Ce fet li deables qi en tel", label_uniform="diable", morph="None"),
    WordToken(corpus=1, form="qi", lemma="un", POS="ADVgen", context="fet li deables qi en tel maniere", label_uniform="un", morph="None"),
    WordToken(corpus=1, form="en", lemma="en1", POS="PRE", context="li deables qi en tel maniere les", label_uniform="en1", morph="None"),
    WordToken(corpus=1, form="tel", lemma="tel", POS="DETind", context="deables qi en tel maniere les a", label_uniform="tel", morph="None"),
    WordToken(corpus=1, form="maniere", lemma="maniere", POS="NOMcom", context="qi en tel maniere les a laciez", label_uniform="maniere", morph="None"),
    WordToken(corpus=1, form="les", lemma="il", POS="PROper", context="en tel maniere les a laciez et", label_uniform="il", morph="None"),
    WordToken(corpus=1, form="a", lemma="a", POS="VERcjg", context="tel maniere les a laciez et pris", label_uniform="a", morph="None"),
    WordToken(corpus=1, form="laciez", lemma="lacier", POS="VERppe", context="maniere les a laciez et pris q", label_uniform="lacier", morph="None"),
    WordToken(corpus=1, form="et", lemma="et", POS="CONcoo", context="les a laciez et pris q il", label_uniform="et", morph="None"),
    WordToken(corpus=1, form="pris", lemma="prendre", POS="VERppe", context="a laciez et pris q il les", label_uniform="prendre", morph="None"),
    WordToken(corpus=1, form="q", lemma=":", POS="PONfrt", context="laciez et pris q il les enmeine", label_uniform=":", morph="None"),
    WordToken(corpus=1, form="il", lemma="il", POS="PROper", context="et pris q il les enmeine en", label_uniform="il", morph="None"),
    WordToken(corpus=1, form="les", lemma="il", POS="PROper", context="pris q il les enmeine en infer", label_uniform="il", morph="None"),
    WordToken(corpus=1, form="enmeine", lemma="enoiier", POS="VERcjg", context="q il les enmeine en infer le", label_uniform="enoiier", morph="None"),
    WordToken(corpus=1, form="en", lemma="en2", POS="PROadv", context="il les enmeine en infer le grant", label_uniform="en2", morph="None"),
    WordToken(corpus=1, form="infer", lemma="inde", POS="VERinf", context="les enmeine en infer le grant chemin", label_uniform="inde", morph="None"),
    WordToken(corpus=1, form="le", lemma="le", POS="DETdef", context="enmeine en infer le grant chemin plenier", label_uniform="le", morph="None"),
    WordToken(corpus=1, form="grant", lemma="grant", POS="ADJqua", context="en infer le grant chemin plenier .", label_uniform="grant", morph="None"),
    WordToken(corpus=1, form="chemin", lemma="chemin", POS="NOMcom", context="infer le grant chemin plenier . De", label_uniform="chemin", morph="None"),
    WordToken(corpus=1, form="plenier", lemma="plenier2", POS="VERinf", context="le grant chemin plenier . De ce", label_uniform="plenier2", morph="None"),
    WordToken(corpus=1, form=".", lemma=".", POS="PONfrt", context="grant chemin plenier . De ce se", label_uniform=".", morph="None"),
    WordToken(corpus=1, form="De", lemma="de", POS="PRE", context="chemin plenier . De ce se gardent", label_uniform="de", morph="None"),
    WordToken(corpus=1, form="ce", lemma="ce1", POS="PROdem", context="plenier . De ce se gardent li", label_uniform="ce1", morph="None"),
    WordToken(corpus=1, form="se", lemma="soi1", POS="PROper", context=". De ce se gardent li seint", label_uniform="soi1", morph="None"),
    WordToken(corpus=1, form="gardent", lemma="garder", POS="VERcjg", context="De ce se gardent li seint home", label_uniform="garder", morph="None"),
    WordToken(corpus=1, form="li", lemma="le", POS="PROper", context="ce se gardent li seint home qi", label_uniform="le", morph="None"),
    WordToken(corpus=1, form="seint", lemma="saint", POS="VERcjg", context="se gardent li seint home qi par", label_uniform="saint", morph="None"),
    WordToken(corpus=1, form="home", lemma="ome", POS="NOMcom", context="gardent li seint home qi par dolereuses", label_uniform="ome", morph="None"),
    WordToken(corpus=1, form="qi", lemma="ci", POS="ADVgen", context="li seint home qi par dolereuses peinnes", label_uniform="ci", morph="None"),
    WordToken(corpus=1, form="par", lemma="par", POS="PRE", context="seint home qi par dolereuses peinnes et", label_uniform="par", morph="None"),
    WordToken(corpus=1, form="dolereuses", lemma="doloros", POS="ADJqua", context="home qi par dolereuses peinnes et par", label_uniform="doloros", morph="None"),
    WordToken(corpus=1, form="peinnes", lemma="peine", POS="NOMcom", context="qi par dolereuses peinnes et par griez", label_uniform="peine", morph="None"),
    WordToken(corpus=1, form="et", lemma="et", POS="CONcoo", context="par dolereuses peinnes et par griez tormenz", label_uniform="et", morph="None"),
    WordToken(corpus=1, form="par", lemma="par", POS="PRE", context="dolereuses peinnes et par griez tormenz et", label_uniform="par", morph="None"),
    WordToken(corpus=1, form="griez", lemma="grief", POS="ADJqua", context="peinnes et par griez tormenz et par", label_uniform="grief", morph="None"),
    WordToken(corpus=1, form="tormenz", lemma="tornëiz", POS="VERppe", context="et par griez tormenz et par veilles", label_uniform="torneiz", morph="None"),
    WordToken(corpus=1, form="et", lemma="et", POS="CONcoo", context="par griez tormenz et par veilles et", label_uniform="et", morph="None"),
    WordToken(corpus=1, form="par", lemma="par", POS="PRE", context="griez tormenz et par veilles et par", label_uniform="par", morph="None"),
    WordToken(corpus=1, form="veilles", lemma="veillier2", POS="NOMcom", context="tormenz et par veilles et par geunes", label_uniform="veillier2", morph="None"),
    WordToken(corpus=1, form="et", lemma="et", POS="CONcoo", context="et par veilles et par geunes et", label_uniform="et", morph="None"),
    WordToken(corpus=1, form="par", lemma="par", POS="PRE", context="par veilles et par geunes et par", label_uniform="par", morph="None"),
    WordToken(corpus=1, form="geunes", lemma="jëuner", POS="NOMcom", context="veilles et par geunes et par toutes", label_uniform="jeuner", morph="None"),
    WordToken(corpus=1, form="et", lemma="et", POS="CONcoo", context="et par geunes et par toutes bones", label_uniform="et", morph="None"),
    WordToken(corpus=1, form="par", lemma="par", POS="PRE", context="par geunes et par toutes bones oevres", label_uniform="par", morph="None"),
    WordToken(corpus=1, form="toutes", lemma="tort1", POS="NOMcom", context="geunes et par toutes bones oevres firent", label_uniform="tort1", morph="None"),
    WordToken(corpus=1, form="bones", lemma="bon", POS="ADJqua", context="et par toutes bones oevres firent tant", label_uniform="bon", morph="None"),
    WordToken(corpus=1, form="oevres", lemma="uevre", POS="NOMcom", context="par toutes bones oevres firent tant q", label_uniform="uevre", morph="None"),
    WordToken(corpus=1, form="firent", lemma="faire", POS="VERcjg", context="toutes bones oevres firent tant q il", label_uniform="faire", morph="None"),
    WordToken(corpus=1, form="tant", lemma="tant", POS="ADVgen", context="bones oevres firent tant q il vindrent", label_uniform="tant", morph="None"),
    WordToken(corpus=1, form="q", lemma="que4", POS="CONsub", context="oevres firent tant q il vindrent a", label_uniform="que4", morph="None"),
    WordToken(corpus=1, form="il", lemma="il", POS="PROper", context="firent tant q il vindrent a vie", label_uniform="il", morph="None"),
    WordToken(corpus=1, form="vindrent", lemma="venir", POS="VERcjg", context="tant q il vindrent a vie parmenable", label_uniform="venir", morph="None"),
    WordToken(corpus=1, form="a", lemma="a", POS="PRE", context="q il vindrent a vie parmenable et", label_uniform="a", morph="None"),
    WordToken(corpus=1, form="vie", lemma="vie", POS="NOMcom", context="il vindrent a vie parmenable et a", label_uniform="vie", morph="None"),
    WordToken(corpus=1, form="parmenable", lemma="parmenidés", POS="NOMpro", context="vindrent a vie parmenable et a la", label_uniform="parmenides", morph="None"),
    WordToken(corpus=1, form="et", lemma="et", POS="CONcoo", context="a vie parmenable et a la corone", label_uniform="et", morph="None"),
    WordToken(corpus=1, form="a", lemma="a", POS="PRE", context="vie parmenable et a la corone de", label_uniform="a", morph="None"),
    WordToken(corpus=1, form="la", lemma="le", POS="DETdef", context="parmenable et a la corone de gloire", label_uniform="le", morph="None"),
    WordToken(corpus=1, form="corone", lemma="corone", POS="NOMcom", context="et a la corone de gloire .", label_uniform="corone", morph="None"),
    WordToken(corpus=1, form="de", lemma="de", POS="PRE", context="a la corone de gloire . A", label_uniform="de", morph="None"),
    WordToken(corpus=1, form="gloire", lemma="gloire", POS="NOMcom", context="la corone de gloire . A ce", label_uniform="gloire", morph="None"),
    WordToken(corpus=1, form=".", lemma=".", POS="PONfrt", context="corone de gloire . A ce regarderent", label_uniform=".", morph="None"),
    WordToken(corpus=1, form="A", lemma="a", POS="PRE", context="de gloire . A ce regarderent li", label_uniform="a", morph="None"),
    WordToken(corpus=1, form="ce", lemma="ce1", POS="PROdem", context="gloire . A ce regarderent li seint", label_uniform="ce1", morph="None"),
    WordToken(corpus=1, form="regarderent", lemma="regarder", POS="VERcjg", context=". A ce regarderent li seint confessors", label_uniform="regarder", morph="None"),
    WordToken(corpus=1, form="li", lemma="le", POS="PROper", context="A ce regarderent li seint confessors et", label_uniform="le", morph="None"),
    WordToken(corpus=1, form="seint", lemma="saint", POS="VERcjg", context="ce regarderent li seint confessors et mes", label_uniform="saint", morph="None"),
    WordToken(corpus=1, form="confessors", lemma="confesser", POS="NOMcom", context="regarderent li seint confessors et mes sires", label_uniform="confesser", morph="None"),
    WordToken(corpus=1, form="et", lemma="et", POS="CONcoo", context="li seint confessors et mes sires seinz", label_uniform="et", morph="None"),
    WordToken(corpus=1, form="mes", lemma="mon1", POS="DETpos", context="seint confessors et mes sires seinz Martins", label_uniform="mon1", morph="None"),
    WordToken(corpus=1, form="sires", lemma="seignor", POS="NOMcom", context="confessors et mes sires seinz Martins dont", label_uniform="seignor", morph="None"),
    WordToken(corpus=1, form="seinz", lemma="saint", POS="VERcjg", context="et mes sires seinz Martins dont ci", label_uniform="saint", morph="None"),
    WordToken(corpus=1, form="Martins", lemma="martin", POS="NOMpro", context="mes sires seinz Martins dont ci comence", label_uniform="martin", morph="None"),
    WordToken(corpus=1, form="dont", lemma="dont", POS="PROrel", context="sires seinz Martins dont ci comence la", label_uniform="dont", morph="None"),
    WordToken(corpus=1, form="ci", lemma="ci", POS="ADVgen", context="seinz Martins dont ci comence la vie", label_uniform="ci", morph="None"),
    WordToken(corpus=1, form="comence", lemma="comencier", POS="VERcjg", context="Martins dont ci comence la vie .", label_uniform="comencier", morph="None"),
    WordToken(corpus=1, form="la", lemma="le", POS="DETdef", context="dont ci comence la vie . Seinz", label_uniform="le", morph="None"),
    WordToken(corpus=1, form="vie", lemma="vie", POS="NOMcom", context="ci comence la vie . Seinz Martins", label_uniform="vie", morph="None"),
    WordToken(corpus=1, form=".", lemma=".", POS="PONfrt", context="comence la vie . Seinz Martins fu", label_uniform=".", morph="None"),
    WordToken(corpus=1, form="Seinz", lemma="saint", POS="VERppa", context="la vie . Seinz Martins fu nez", label_uniform="saint", morph="None"),
    WordToken(corpus=1, form="Martins", lemma="martin", POS="NOMpro", context="vie . Seinz Martins fu nez de", label_uniform="martin", morph="None"),
    WordToken(corpus=1, form="fu", lemma="estre1", POS="VERcjg", context=". Seinz Martins fu nez de la", label_uniform="estre1", morph="None"),
    WordToken(corpus=1, form="nez", lemma="naistre", POS="VERppe", context="Seinz Martins fu nez de la contree", label_uniform="naistre", morph="None"),
    WordToken(corpus=1, form="de", lemma="de", POS="PRE", context="Martins fu nez de la contree de", label_uniform="de", morph="None"),
    WordToken(corpus=1, form="la", lemma="le", POS="DETdef", context="fu nez de la contree de Pannone", label_uniform="le", morph="None"),
    WordToken(corpus=1, form="contree", lemma="contree", POS="NOMcom", context="nez de la contree de Pannone ,", label_uniform="contree", morph="None"),
    WordToken(corpus=1, form="de", lemma="de", POS="PRE", context="de la contree de Pannone , d", label_uniform="de", morph="None"),
    WordToken(corpus=1, form="Pannone", lemma="prendre", POS="NOMcom", context="la contree de Pannone , d un", label_uniform="prendre", morph="None"),
    WordToken(corpus=1, form=",", lemma=",", POS="PONfbl", context="contree de Pannone , d un chastiel", label_uniform=",", morph="None"),
    WordToken(corpus=1, form="d", lemma="de", POS="PRE", context="de Pannone , d un chastiel qi", label_uniform="de", morph="None"),
    WordToken(corpus=1, form="un", lemma="un", POS="DETndf", context="Pannone , d un chastiel qi Ysabbarie", label_uniform="un", morph="None"),
    WordToken(corpus=1, form="chastiel", lemma="chastiier", POS="NOMcom", context=", d un chastiel qi Ysabbarie avoit", label_uniform="chastiier", morph="None"),
    WordToken(corpus=1, form="qi", lemma="ci", POS="DETndf", context="d un chastiel qi Ysabbarie avoit non", label_uniform="ci", morph="None"),
    WordToken(corpus=1, form="Ysabbarie", lemma="chamberiere", POS="ADJqua", context="un chastiel qi Ysabbarie avoit non .", label_uniform="chamberiere", morph="None"),
    WordToken(corpus=1, form="avoit", lemma="avoir", POS="VERcjg", context="chastiel qi Ysabbarie avoit non . Si", label_uniform="avoir", morph="None"),
    WordToken(corpus=1, form="non", lemma="nom", POS="NOMcom", context="qi Ysabbarie avoit non . Si fu", label_uniform="nom", morph="None"),
    WordToken(corpus=1, form=".", lemma=".", POS="PONfrt", context="Ysabbarie avoit non . Si fu de", label_uniform=".", morph="None"),
    WordToken(corpus=1, form="Si", lemma="si", POS="ADVgen", context="avoit non . Si fu de haute", label_uniform="si", morph="None"),
    WordToken(corpus=1, form="fu", lemma="estre1", POS="VERcjg", context="non . Si fu de haute lignie", label_uniform="estre1", morph="None"),
    WordToken(corpus=1, form="de", lemma="de", POS="PRE", context=". Si fu de haute lignie et", label_uniform="de", morph="None"),
    WordToken(corpus=1, form="haute", lemma="haut", POS="ADJqua", context="Si fu de haute lignie et de", label_uniform="haut", morph="None"),
    WordToken(corpus=1, form="lignie", lemma="lignage", POS="NOMcom", context="fu de haute lignie et de par", label_uniform="lignage", morph="None"),
    WordToken(corpus=1, form="et", lemma="et", POS="CONcoo", context="de haute lignie et de par mere", label_uniform="et", morph="None"),
    WordToken(corpus=1, form="de", lemma="de", POS="PRE", context="haute lignie et de par mere et", label_uniform="de", morph="None"),
    WordToken(corpus=1, form="par", lemma="par", POS="PRE", context="lignie et de par mere et de", label_uniform="par", morph="None"),
    WordToken(corpus=1, form="mere", lemma="mere", POS="NOMcom", context="et de par mere et de par", label_uniform="mere", morph="None"),
    WordToken(corpus=1, form="et", lemma="et", POS="CONcoo", context="de par mere et de par pere", label_uniform="et", morph="None"),
    WordToken(corpus=1, form="de", lemma="de", POS="PRE", context="par mere et de par pere .", label_uniform="de", morph="None"),
    WordToken(corpus=1, form="par", lemma="par", POS="PRE", context="mere et de par pere . Ses", label_uniform="par", morph="None"),
    WordToken(corpus=1, form="pere", lemma="pere", POS="NOMcom", context="et de par pere . Ses peres", label_uniform="pere", morph="None"),
    WordToken(corpus=1, form=".", lemma=".", POS="PONfrt", context="de par pere . Ses peres fu", label_uniform=".", morph="None"),
    WordToken(corpus=1, form="Ses", lemma="son4", POS="DETpos", context="par pere . Ses peres fu chevaliers", label_uniform="son4", morph="None"),
    WordToken(corpus=1, form="peres", lemma="pere", POS="NOMcom", context="pere . Ses peres fu chevaliers et", label_uniform="pere", morph="None"),
    WordToken(corpus=1, form="fu", lemma="estre1", POS="VERcjg", context=". Ses peres fu chevaliers et hauz", label_uniform="estre1", morph="None"),
    WordToken(corpus=1, form="chevaliers", lemma="chevalier", POS="NOMcom", context="Ses peres fu chevaliers et hauz hom", label_uniform="chevalier", morph="None"),
    WordToken(corpus=1, form="et", lemma="et", POS="CONcoo", context="peres fu chevaliers et hauz hom et", label_uniform="et", morph="None"),
    WordToken(corpus=1, form="hauz", lemma="haut", POS="ADJqua", context="fu chevaliers et hauz hom et riches", label_uniform="haut", morph="None"),
    WordToken(corpus=1, form="hom", lemma="ome", POS="NOMcom", context="chevaliers et hauz hom et riches .", label_uniform="ome", morph="None"),
    WordToken(corpus=1, form="et", lemma="et", POS="CONcoo", context="et hauz hom et riches . Et", label_uniform="et", morph="None"),
    WordToken(corpus=1, form="riches", lemma="riche", POS="ADJqua", context="hauz hom et riches . Et il", label_uniform="riche", morph="None"),
    WordToken(corpus=1, form=".", lemma=".", POS="PONfrt", context="hom et riches . Et il comença", label_uniform=".", morph="None"),
    WordToken(corpus=1, form="Et", lemma="et", POS="CONcoo", context="et riches . Et il comença tres", label_uniform="et", morph="None"),
    WordToken(corpus=1, form="il", lemma="il", POS="PROper", context="riches . Et il comença tres s", label_uniform="il", morph="None"),
    WordToken(corpus=1, form="comença", lemma="comencier", POS="VERcjg", context=". Et il comença tres s enfance", label_uniform="comencier", morph="None"),
    WordToken(corpus=1, form="tres", lemma="très", POS="ADVgen", context="Et il comença tres s enfance bones", label_uniform="tres", morph="None"),
    WordToken(corpus=1, form="s", lemma="soi1", POS="ADVgen", context="il comença tres s enfance bones oevres", label_uniform="soi1", morph="None"),
    WordToken(corpus=1, form="enfance", lemma="enfance", POS="NOMcom", context="comença tres s enfance bones oevres a", label_uniform="enfance", morph="None"),
    WordToken(corpus=1, form="bones", lemma="bon", POS="ADJqua", context="tres s enfance bones oevres a feire", label_uniform="bon", morph="None"),
    WordToken(corpus=1, form="oevres", lemma="uevre", POS="NOMcom", context="s enfance bones oevres a feire et", label_uniform="uevre", morph="None"),
    WordToken(corpus=1, form="a", lemma="a", POS="PRE", context="enfance bones oevres a feire et a", label_uniform="a", morph="None"),
    WordToken(corpus=1, form="feire", lemma="faire", POS="VERinf", context="bones oevres a feire et a ensivre", label_uniform="faire", morph="None"),
    WordToken(corpus=1, form="et", lemma="et", POS="CONcoo", context="oevres a feire et a ensivre ,", label_uniform="et", morph="None"),
    WordToken(corpus=1, form="a", lemma="a", POS="PRE", context="a feire et a ensivre , car", label_uniform="a", morph="None"),
    WordToken(corpus=1, form="ensivre", lemma="ainsi", POS="NOMcom", context="feire et a ensivre , car tres", label_uniform="ainsi", morph="None"),
    WordToken(corpus=1, form=",", lemma=",", POS="PONfbl", context="et a ensivre , car tres ce", label_uniform=",", morph="None"),
    WordToken(corpus=1, form="car", lemma="car", POS="CONcoo", context="a ensivre , car tres ce q", label_uniform="car", morph="None"),
    WordToken(corpus=1, form="tres", lemma="très", POS="ADVgen", context="ensivre , car tres ce q il", label_uniform="tres", morph="None"),
    WordToken(corpus=1, form="ce", lemma="ce2", POS="PROdem", context=", car tres ce q il n", label_uniform="ce2", morph="None"),
    WordToken(corpus=1, form="q", lemma=":", POS="PONfrt", context="car tres ce q il n avoit", label_uniform=":", morph="None"),
    WordToken(corpus=1, form="il", lemma="il", POS="PROper", context="tres ce q il n avoit qe", label_uniform="il", morph="None"),
    WordToken(corpus=1, form="n", lemma="ne1", POS="ADVneg", context="ce q il n avoit qe .", label_uniform="ne1", morph="None"),
    WordToken(corpus=1, form="avoit", lemma="avoir", POS="VERcjg", context="q il n avoit qe . x", label_uniform="avoir", morph="None"),
    WordToken(corpus=1, form="qe", lemma="ce1", POS="PROdem", context="il n avoit qe . x .", label_uniform="ce1", morph="None"),
    WordToken(corpus=1, form=".", lemma=".", POS="PONfrt", context="n avoit qe . x . anz", label_uniform=".", morph="None"),
    WordToken(corpus=1, form="x", lemma="»", POS="PONpdr", context="avoit qe . x . anz ,", label_uniform=">>", morph="None"),
    WordToken(corpus=1, form=".", lemma=".", POS="PONfrt", context="qe . x . anz , comença", label_uniform=".", morph="None"),
    WordToken(corpus=1, form="anz", lemma="an", POS="ADVgen", context=". x . anz , comença il", label_uniform="an", morph="None"),
    WordToken(corpus=1, form=",", lemma=",", POS="PONfbl", context="x . anz , comença il a", label_uniform=",", morph="None"),
    WordToken(corpus=1, form="comença", lemma="comencier", POS="VERcjg", context=". anz , comença il a aler", label_uniform="comencier", morph="None"),
    WordToken(corpus=1, form="il", lemma="il", POS="PROper", context="anz , comença il a aler a", label_uniform="il", morph="None"),
    WordToken(corpus=1, form="a", lemma="a", POS="PRE", context=", comença il a aler a seinte", label_uniform="a", morph="None"),
    WordToken(corpus=1, form="aler", lemma="aler", POS="VERinf", context="comença il a aler a seinte glisse", label_uniform="aler", morph="None"),
    WordToken(corpus=1, form="a", lemma="a", POS="PRE", context="il a aler a seinte glisse maugré", label_uniform="a", morph="None"),
    WordToken(corpus=1, form="seinte", lemma="saint", POS="ADJqua", context="a aler a seinte glisse maugré son", label_uniform="saint", morph="None")
]

WauchierAllowedLemma = [
    AllowedLemma(label="de", label_uniform="de", corpus=Wauchier.id),
    AllowedLemma(label="saint", label_uniform="saint", corpus=Wauchier.id),
    AllowedLemma(label="martin", label_uniform="martin", corpus=Wauchier.id),
    AllowedLemma(label="öir", label_uniform="öir", corpus=Wauchier.id),
    AllowedLemma(label="car", label_uniform="car", corpus=Wauchier.id),
    AllowedLemma(label="devoir", label_uniform="devoir", corpus=Wauchier.id),
    AllowedLemma(label="entendre", label_uniform="entendre", corpus=Wauchier.id),
    AllowedLemma(label=",", label_uniform=",", corpus=Wauchier.id),
    AllowedLemma(label="par", label_uniform="par", corpus=Wauchier.id),
    AllowedLemma(label="un", label_uniform="un", corpus=Wauchier.id),
    AllowedLemma(label="pöoir", label_uniform="pöoir", corpus=Wauchier.id),
    AllowedLemma(label="il", label_uniform="il", corpus=Wauchier.id),
    AllowedLemma(label="doucement", label_uniform="doucement", corpus=Wauchier.id),
    AllowedLemma(label="en1", label_uniform="en1", corpus=Wauchier.id),
    AllowedLemma(label="le", label_uniform="le", corpus=Wauchier.id),
    AllowedLemma(label="mout", label_uniform="mout", corpus=Wauchier.id),
    AllowedLemma(label="bien", label_uniform="bien", corpus=Wauchier.id),
    AllowedLemma(label="retenir", label_uniform="retenir", corpus=Wauchier.id),
    AllowedLemma(label="volentiers", label_uniform="volentiers", corpus=Wauchier.id),
    AllowedLemma(label="et", label_uniform="et", corpus=Wauchier.id),
    AllowedLemma(label="savoir", label_uniform="savoir", corpus=Wauchier.id)
]

WauchierAllowedPOS = [
    AllowedPOS(label='ADJqua', corpus=Wauchier.id),
    AllowedPOS(label='NOMpro', corpus=Wauchier.id),
    AllowedPOS(label='CONcoo', corpus=Wauchier.id),
    AllowedPOS(label='DETdef', corpus=Wauchier.id),
    AllowedPOS(label='PROper', corpus=Wauchier.id),
    AllowedPOS(label='ADVgen', corpus=Wauchier.id),
    AllowedPOS(label='PONfbl', corpus=Wauchier.id),
    AllowedPOS(label='VERcjg', corpus=Wauchier.id),
    AllowedPOS(label='PRE', corpus=Wauchier.id),
    AllowedPOS(label='VERinf', corpus=Wauchier.id)
]