name: Test library

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        test_dbms: [postgresql, sqlite]
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: pyrrha
          POSTGRES_PASSWORD: pyrrha
          POSTGRES_DB: data-test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v4
    - uses: browser-actions/setup-chrome@v1 # This ensures compatibility with nektos/act
    - uses: nanasess/setup-chromedriver@v2 # This ensures compatibility with nektos/act
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov coveralls flake8 pytest-sugar
    - name: Set up TEST_DATABASE_URL
      run: |
        echo "TEST_DATABASE_URL=postgresql://pyrrha:pyrrha@localhost:5432/data-test" >> $GITHUB_ENV
      if: matrix.test_dbms == 'postgresql'
    - name: Test with nose
      run: |
        pytest --doctest-modules --cov=app --verbose --cov-report=lcov
    - name: Coveralls Python
      if: matrix.test_dbms == 'postgresql'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        coveralls
